### ISSUE TITLE
Help needed for object handling in font dialog

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1169]
This is related to #1075 and blocks merging of that PR, regardless of any other review.

When the Font Dialog has once been opened (more concretely: the `MusicPreviewWidget` in it), there will be an exception upon closing Frescobaldi:

```
Traceback (most recent call last):
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi", line 32, in <module>
    sys.exit(app.run())
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/app.py", line 141, in run
    aboutToQuit()
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/musicpreview.py", line 171, in cleanup
    self._top.hide()
RuntimeError: wrapped C/C++ object of type QWidget has been deleted
```

The culprit is that `musicpreview.MusicPreviewWidget` connects its `cleanup` method to `app.aboutToQuit`, and when that is executed the widgets don't exist anymore. Their C++ objects, that is, while Python thinks they are still alive.
This is not specific to the `self._top` object but affects all subwidgets.

IIUC any QObject descendant would properly disconnect itself from all signals upon destruction, and it seems my preview widget does not do that correctly. The strange thing is that the same `MusicPreviewWidget` does *not* show the same behaviour inside the Score Wizard's score preview. Also that preview seems to properly disconnect from the job's signals when the dialog is closed while the preview job is still running.

Obviously I have done one tiny "parenting" error somewhere that I just don't find. I assume there is a reference that keeps the Python object alive but does not prevent the C++ object to be garbage collected.

Does anyone have an idea, @wbsoft  or anyone else?

**Comment by uliska** [comment]
There are several peculiarities with the Document Fonts dialog that may be related to the same cause. Of course the exception described in the initial comment is the most serious issue, but others (so far I see two more) are also annoying and should be cleaned up before merging:

**1)**
Closing the dialog does *not* cut ties with running jobs.
When starting the preview job, its `output` and `done` signals are connected, but when the dialog is closed while the job is still running these connections are not automatically disconnected, resulting in exceptions when the signals are emitted and call by-now-destroyed handlers.

I cured the symptoms with this additional method in `musicpreview.MusicPreviewWidget`

https://github.com/frescobaldi/frescobaldi/blob/665c415301bfe7d86a5132e7913c4f117952af18/frescobaldi_app/musicpreview.py#L92-L100

which is called before closing the Font dialog with

https://github.com/frescobaldi/frescobaldi/blob/665c415301bfe7d86a5132e7913c4f117952af18/frescobaldi_app/fonts/dialog.py#L166-L168

However, I find this troubling and unclean. I don't see why such efforts should be necessary (especially since the dialog has other possibly related issues). What's more: The music preview widget as used in the preview dialog from the score wizard does *not* show this behaviour.

**2)**
Clicking on the `Help` button expectedly starts the user guide and opens the requested page, but the userguide window is stacked *behind* the dialog. I'm not sure whether the dialog insists on staying in front or whether the userguide is instantiated wrongly, but I strongly suspect the underlying issue is the same for all symptoms.
