### ISSUE TITLE
Manuscript viewer doesn't save opened files (anymore?)

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1218]
I notice that the manuscript viewer forgets the opened document(s) when closing Frescobaldi or switching sessions (if I switch sessions the open documents are closed but no other ones opened).

Is this related to the QPageView changes?

**Comment by wbsoft** [comment]
Thanks for reporting. Will look into it!

**Comment by wbsoft** [comment]
Not qpageview caused the bug but commit 2e0dd76218b0068616de366c62a41716e733d956.
We were not aware that the saved entries are not just file names, but tuples of (filename, position). I am working on a fix.

**Comment by uliska** [comment]
**IMPORTANT:** (Help needed)

For the record (not sure but suspect it's related): After switching sessions I got the following error, which also prevents me from launching Frescobaldi:

```
Traceback (most recent call last):
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi", line 32, in <module>
    sys.exit(app.run())
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/app.py", line 145, in run
    appStarted()
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
  File "/home/uliska/git/frescobaldi/extensions/lm-vs-frescobaldi-extension/examples.py", line 205, in app_started
    self.slot_current_doc_updated(self.extension().current_document(), None)
  File "/home/uliska/git/frescobaldi/extensions/lm-vs-frescobaldi-extension/examples.py", line 504, in slot_current_doc_updated
    self.select_example(new_name)
  File "/home/uliska/git/frescobaldi/extensions/lm-vs-frescobaldi-extension/examples.py", line 395, in select_example
    self.show_manuscript(name)
  File "/home/uliska/git/frescobaldi/extensions/lm-vs-frescobaldi-extension/examples.py", line 481, in show_manuscript
    manuscript_viewer.setCurrentPage(page)
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/viewers/__init__.py", line 219, in setCurrentPage
    self.widget().view.setCurrentPageNumber(num)
  File "/home/uliska/git/lilypond/frescobaldi/frescobaldi_app/qpageview/view.py", line 191, in setCurrentPageNumber
    self.ensureVisible(page.geometry(), margins, self.kineticPagingEnabled)
AttributeError: 'NoneType' object has no attribute 'geometry'
```
Frescobaldi will now launch into the GUI, show the Exception handler and after that closes. The Music View is already loaded, but the Manuscript Viewer has an empty main widget.

Starting with no session doesn't help.

I didn't find a way to disable the manuscript view within the config file. Aren't tool panels and their state/dock stored there?

Right now I don't see a way to start Frescobaldi on this computer!

**Comment by wbsoft** [comment]
Just checkout a few commits behind:-) thanks for reporting!

**Comment by wbsoft** [comment]
I think your extension is calling into the manuscript viewer to set the current page without a (valid) document being loaded. But I will fix qpageview so that it does not throw the error.

**Comment by uliska** [comment]
That is probably true (but is tangentially related to the fact that the manuscript viewer forgets the loaded document).

Ah yes, now I see that the issue is properly reported as an "extension error", and when clicking on "Email bug report" my own address (i.e. the extension maintainer's) is used ;-)

OK, basically that's an extension error, and I can start Frescobaldi after disabling that line in the extension. But still I'd say Frescobaldi should be resilient to this.

**Comment by wbsoft** [comment]
Please check current master, qpageview should now not error out when setCurrentPageNumber is called with no pages loaded.

**Comment by wbsoft** [comment]
(I committed using my smartphone, can't test right now but I guess it will work)

**Comment by uliska** [comment]
Thanks!
Yes, it works.

> (I committed using my smartphone, can't test right now but I guess it will work)

Maybe I'll be using the exchange over the last half hour in a blog post someday ;-)

**Comment by wbsoft** [comment]
😁👍
