### ISSUE TITLE
Windows - new installer works only on clean installation

### ISSUE THREAD

**Issue by zhch333** [frescobaldi/frescobaldi#1252]
3.0.1 works but the newest one throws errors after trying to start the program (no errors during installation).

**Comment by uliska** [comment]
Well, it would be good to know what errors.

We installed the 3.1.1 installer from Github on a bunch of Windows 10 machines yesterday and didn't have any issues.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by zhch333** [comment]
Sure, but I had to re-install the 3.1.1 Version again. And then hand-type the Error, because it is not possible to select and copy-paste text from this window... here you go:

(Window-Title: cx_Freeze: Python error in main script)
Traceback (most recent call last):
File
"C:\Users\Jones.000\Envs\Frescobaldi_5.13\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
File
"C:\Users\Jones.000\Envs\Frescobaldi_5.13\lib\site-packages\cs_Freeze\initscripts\Console.py", line 23, in run
File "../frescobaldi", line 24, in <module>
File "C:\Program Files (x86)\Frescobaldi\frescobaldi_app\main.py", line 29, in <module>
 from PyQt5.QtCore import QSettings, QTimer,QUrl
Import Error: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.

**Comment by fedelibre** [comment]
I think I've seen this before.. it happens when you install without uninstalling a previous version first. Can you confirm?
Try uninstalling every Frescobaldi version you have and then install again version 3.1.1. Let us know if you get the same error or not.

**Comment by zhch333** [comment]
Did as told - and everything works now. Thank you!

**Comment by wbsoft** [comment]
The old 2.0 installer neatly removed itself when updating or reinstalling. Maybe that can be added into the new installer?

**Comment by fedelibre** [comment]
Let's reopen it so we hopefully don't get tons of duplicate reports.

**Comment by grstatdoc-gr** [comment]
I have encountered a similar error in running Frescobaldi 3.1.2. While deleting all of the previous installations and installing  as an administrator, I got it to run OK. But after putting a shortcut on the desktop and starting it from the shortcut, I encountered the error shown in the screenshot attached. After running the shortcut as an administrator, Frescobaldi 3.1.2 opened OK
![Screenshot 2020-09-23 181345](https://user-images.githubusercontent.com/71800985/94090928-c3008100-fdcb-11ea-8980-acf21c5763fa.png)

**Comment by fedelibre** [comment]
The next Windows installer will use a different build tool and shouldn't have this problem.
