### ISSUE TITLE
Frescobaldi 3.1.1 don't even start...

### ISSUE THREAD

**Issue by m4xv1el** [frescobaldi/frescobaldi#1267]
...on a iMac mid 2011 with 16GB Ram and MacOS 10.13.6
A few secondsafter the attempt of starting it unexpectedly crashes. No other comment.

**Comment by dliessi** [comment]
Probably #1244.

Can you please open a Terminal, run the following line and report any resulting message?
```
/Applications/Frescobaldi.app/Contents/MacOS/Frescobaldi
```
(If you renamed the application bundle, or it is not in the `/Applications` directory, you need to adapt the line accordingly.)

**Comment by nodevnul** [comment]
I had copied Frescobaldi 3.1.2 on macOS 10.13.6 (MBP 15" 2010) and on macOS 10.14.6 (MacPro 5.1 12C). It launched as expected. SVG non functional.

I also just downloaded the 3.1.1 dmg and launched Frescobaldi from the image without problems.

**Comment by tsgouros** [comment]
On a Mac, 10.12.6, I installed Frescobaldi 3.1.2 via Homebrew and via the DMG. Both bombed immediately. Using the Homebrew version, I ran it from the command line, and got the following:

```
Downloads$ brew cask install frescobaldi
==> Downloading https://github.com/frescobaldi/frescobaldi/releases/download/v3.1.2/F
Already downloaded: /Users/.../Library/Caches/Homebrew/downloads/895de62dfbc6dfbd1079d74fe8c27a5e5a324e1eb20d369c97bc101e56c014b2--Frescobaldi-3.1.2-x86_64.dmg
==> Verifying SHA-256 checksum for Cask 'frescobaldi'.
==> Installing Cask frescobaldi
==> Moving App 'Frescobaldi.app' to '/Applications/Frescobaldi.app'.
🍺  frescobaldi was successfully installed!
Downloads$ /Applications/Frescobaldi.app/Contents/MacOS/Frescobaldi 
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/__boot__.py", line 411, in <module>
    _run()
  File "/Applications/Frescobaldi.app/Contents/Resources/__boot__.py", line 394, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/Frescobaldi.app/Contents/Resources/frescobaldi", line 24, in <module>
    import main
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/main.py", line 29, in <module>
    from PyQt5.QtCore import QSettings, QTimer, QUrl
  File "PyQt5/QtCore.pyc", line 14, in <module>
  File "PyQt5/QtCore.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: dlopen(/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/lib-dynload/PyQt5/QtCore.so, 2): Symbol not found: _futimens
  Referenced from: /Applications/Frescobaldi.app/Contents/MacOS/../Frameworks/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Frescobaldi.app/Contents/MacOS/../Frameworks/QtCore.framework/Versions/5/QtCore
2020-08-09 22:45:42.515 Frescobaldi[90863:5257937] Frescobaldi Error
Downloads$ 
```
Any suggestions?  Thank you.

**Comment by nodevnul** [comment]
> On a Mac, 10.12.6, I installed Frescobaldi 3.1.2 via Homebrew and via the DMG. Both bombed immediately. Using the Homebrew version, I ran it from the command line, and got the following:
> 

I don't know for Homebrew or Macports installations - because I never used them so far - but for the native macOS build you might want to check:

1. Console-Logs. Console-Logs are in most cases the first place to look at. Run Console (Applications --> Utilities). Make shure that your device is selected in the left sidebar-list. Now launch Frescobaldi from the dmg and whatch Console with possible new entries. These may contain valuable information on what errors appeared.

2. Install Xcode from Apple developer downloads for your particular macOS Version. As i recall in Xcode you can analyze the launch and running of an application step by step - like scrubbing a soundfile in a DAW. Maybe there is any information for the very moment of the crash.

May these infos be valuable for the coders ?

**Comment by tsgouros** [comment]
My error is an exact reproduction of the problem described in #1233. Don't know why my search didn't find that one first. Sorry about that.
