### ISSUE TITLE
Crash on startup: "namespace packages do not have loaders"

### ISSUE THREAD

**Issue by abrock** [frescobaldi/frescobaldi#1302]
When trying to start Frescobaldi it immediately crashes:

```Traceback (most recent call last):
  File "/home/alexander/scripts/frescobaldi", line 34, in <module>
    import checks                   # check whether Frescobaldi really can run
  File "/home/alexander/media/sw/frescobaldi/frescobaldi_app/checks.py", line 94, in <module>
    if not importlib.find_loader('qpageview'):
  File "/home/alexander/anaconda3/lib/python3.7/importlib/__init__.py", line 105, in find_loader
    name=name)
ImportError: namespace packages do not have loaders
```

I did a git bisect and the first bad commit is b14b350746a064c9896e6314bb12c0550be5bfa8
Full bisect log:

```
git bisect start
 bad: [00e5d22cb0309d10f8657ac78a577909a897c8c3] Add the NEWS file (replacing the ChangeLog file)
git bisect bad 00e5d22cb0309d10f8657ac78a577909a897c8c3
 good: [1b025c3414cd20f3740e1cf1046167dbe56214a9] Merge branch 'master' of github.com:frescobaldi/frescobaldi
git bisect good 1b025c3414cd20f3740e1cf1046167dbe56214a9
 good: [2e74386dd9298584d52ed8fca1b111b7f937ba49] move Python version check from startup script to checks module
git bisect good 2e74386dd9298584d52ed8fca1b111b7f937ba49
 bad: [477d7b5cf74392e166ba83789830ffc7a98104ff] add some strings from Qt that were not in the dummy messages list
git bisect bad 477d7b5cf74392e166ba83789830ffc7a98104ff
 bad: [c4705df59336a5881e8a62763e5f97db1e1da06c] list qpageview version in debuginfo
git bisect bad c4705df59336a5881e8a62763e5f97db1e1da06c
 bad: [b14b350746a064c9896e6314bb12c0550be5bfa8] on the road to 3.2, qpageview is now a separate module
git bisect bad b14b350746a064c9896e6314bb12c0550be5bfa8
 first bad commit: [b14b350746a064c9896e6314bb12c0550be5bfa8] on the road to 3.2, qpageview is now a separate module ```

**Comment by fedelibre** [comment]
I cannot reproduce it. I'm just updating the settings to run Frescobaldi from source in my desktop computer. If qpageview is not installed and I launch Frescobaldi, I get a nice dialog saying `The 'qpageview' module can't be found.`.

It seems you're running a custom Python installation. Don't know if this matters...
I'm using Python 3.8.2 from Fedora 32 repository.

How are you running Frescobaldi?
Did you install qpageview or set up the symlink?
Please provide as many details as possible.

**Comment by abrock** [comment]
I installed qpageview (again? not sure) and now it works again, thank you very much.
I just checked out the frescobaldi repo and put a softlink to the file "frescobaldi" in a directory which is in my PATH.

**Comment by fedelibre** [comment]
I was able to reproduce your error. It happens if you symlink to the root directory of the qpageview repository instead of its qpageview subdirectory.

This is the error:

```
$ python frescobaldi
Traceback (most recent call last):
  File "frescobaldi", line 34, in <module>
    import checks                   # check whether Frescobaldi really can run
  File "/home/fede/src/frescobaldi/frescobaldi_app/checks.py", line 94, in <module>
    if not importlib.find_loader('qpageview'):
  File "/usr/lib64/python3.8/importlib/__init__.py", line 104, in find_loader
    raise ImportError('namespace packages do not have loaders',
ImportError: namespace packages do not have loaders
```

Debug and fix:

```
$ ls -l frescobaldi_app/qpageview
lrwxrwxrwx. 1 fede fede 24 19 mag 12.36 frescobaldi_app/qpageview -> /home/fede/src/qpageview

$ rm frescobaldi_app/qpageview

$ ln -s ~/src/qpageview/qpageview frescobaldi_app/qpageview

$ ls -l frescobaldi_app/qpageview
lrwxrwxrwx. 1 fede fede 34 19 mag 12.43 frescobaldi_app/qpageview -> /home/fede/src/qpageview/qpageview
```
