### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type ViewHighlighter has been deleted 

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#1342]
Reported by a user:
> Frescobaldi: 3.1.2
> Extension API: 0.9.0
> Python: 3.7.8
> python-ly: 0.9.5
> Qt: 5.11.3
> PyQt: 5.15.0
> sip: 4.19.23
> poppler: 0.83.0
> python-poppler-qt: 0.75.0
> OS: Darwin-20.1.0-x86_64-i386-64bit
> installation kind: standalone .app bundle
> 
> Traceback (most recent call last):
>   File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/preferences/__init__.py", line 112, in done
>  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/preferences/__init__.py", line 142, in saveSettings
> File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/signals.py", line 191, in emit
> File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/signals.py", line 308, in call
> File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/viewhighlighter.py", line 93, in readSettings
> File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/viewhighlighter.py", line 77, in updateCursor
> RuntimeError: wrapped C/C++ object of type ViewHighlighter has been deleted

Can't reproduce on  my Linux dev system.

**Comment by fedelibre** [comment]
Hopefully fixed in version 4.0.2 by #1935
