### ISSUE TITLE
Crashes on startup in KDE neon 20.04

### ISSUE THREAD

**Issue by DWW256** [frescobaldi/frescobaldi#1384]
If this is a KDE neon problem, then I'll pass it on to them.  But I thought I would run it by you all first.

After a recent update to KDE neon, I have discovered that Frescobaldi now crashes on startup.  This happens regardless of whether I am using 3.0.0, packaged with Ubuntu, or 3.1.3 downloaded from the GitHub releases page.  Here is the traceback when I run it from bash:

`Traceback (most recent call last):
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/plugin.py", line 79, in instance
    return _instances[cls][obj]
  File "/usr/lib/python3.8/weakref.py", line 383, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f66d55ae4a0; to 'type' at 0x29e8770 (PanelManager)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frescobaldi", line 28, in <module>
    main.main()                     # Parse command line, create windows etc
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/main.py", line 210, in main
    win = mainwindow.MainWindow()
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/mainwindow.py", line 129, in __init__
    self.createMenus()
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/mainwindow.py", line 1105, in createMenus
    menu.createMenus(self)
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/menu.py", line 61, in createMenus
    m.addMenu(menu_file(mainwindow))
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/menu.py", line 95, in menu_file
    m.addMenu(snippet.menu.TemplateMenu(mainwindow))
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/snippet/menu.py", line 146, in __init__
    self.addAction(self.tool().actionCollection.templates_manage)
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/snippet/menu.py", line 58, in tool
    return panelmanager.manager(self.mainwindow()).snippettool
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/panelmanager.py", line 38, in manager
    return PanelManager.instance(mainwindow)
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/plugin.py", line 84, in instance
    result.__init__(obj)
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/panelmanager.py", line 70, in __init__
    self.loadPanel("musicview.MusicViewPanel", "viewers")
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/panelmanager.py", line 107, in loadPanel
    __import__(module_name)
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/musicview/__init__.py", line 52, in <module>
    import pagedview
  File "[path]/frescobaldi-3.1.3/frescobaldi_app/pagedview.py", line 36, in <module>
    import popplerqt5
ValueError: PyCapsule_GetPointer called with incorrect name
`
Thank you for your help!

**Comment by DWW256** [comment]
I know that Frescobaldi is not officially supported on KDE neon, but it would be helpful to have at the very least some explanation as to what is going on here and possible workarounds.  Given the small size of the LilyPond community as a whole, it makes sense that Frescobaldi has almost become an essential part of the LilyPond ecosystem at this point; without it, I'm essentially unable to compose music.  While I understand that it is infeasible to support every possible desktop configuration (especially on Linux!), it seems like "won't run at all on the latest builds of its dependencies" is a pretty severe issue.  I'd try to solve it myself, but I don't know a lick of Python.

And again—if the issue can be isolated to some specific oddity in KDE neon's packaging, then by all means let me know.  But regardless, I feel like people ought to have a solution to running this, be it a documentation warning or a bugfix.

Again, if someone could see if they can figure out what's up, I would appreciate it.  Thank you for your precious time.

**Comment by fedelibre** [comment]
> After a recent update to KDE neon, I have discovered that Frescobaldi now crashes on startup.

I don't think it's related to KDE, but rather to some Qt upgrade. Maybe python-poppler-qt5 should be rebuilt, as in issue #838 
This would be an Ubuntu bug. But I'm just guessing.
Before reporting the issue to Ubuntu, you may try to build and install python-poppler-qt5 in /usr/local (overriding the ubuntu package) and see if you solve the problem.

As a quick solution to run Frescobaldi without any dependency problem I recommend [installing the flatpak package](https://flathub.org/apps/details/org.frescobaldi.Frescobaldi).

**Comment by DWW256** [comment]
I tried running the flatpak, but unfortunately it isn't able to correctly compile files on cifs-mounted filesystems (I store my scores on a network drive).  I suspect this is an issue with the Flatpak sandbox, but I really have no idea.  If you think it's a Frescobaldi issue, I could always…drumroll please…file another bug report!

**Comment by fedelibre** [comment]
Yes, it might be a sandbox permission issue. Install the Flatseal app and try to play with the permissions.

**Comment by DWW256** [comment]
Will do.

I tried to rebuild python-poppler-qt5, but it looks like the place you referenced earlier for getting sipdistutils ([https://www.riverbankcomputing.com/hg/sip/raw-file/tip/sipdistutils.py](https://www.riverbankcomputing.com/hg/sip/raw-file/tip/sipdistutils.py)) is now throwing a 404 error.  So I'm a bit confused there.

**Comment by DWW256** [comment]
Solved the Flatpak issues, thanks!  If you can tell me where I might find a copy of sipdistutils.py then I'll keep trying to troubleshoot that, though.  Would love to keep this excellent IDE running smoothly on my favorite distro.

**Comment by fedelibre** [comment]
> Will do.
> 
> I tried to rebuild python-poppler-qt5, but it looks like the place you referenced earlier for getting sipdistutils (https://www.riverbankcomputing.com/hg/sip/raw-file/tip/sipdistutils.py) is now throwing a 404 error. So I'm a bit confused there.

You may be following out-of-date instructions.
I've just taken some notes in [python-poppler-qt5 wiki](https://github.com/frescobaldi/python-poppler-qt5/wiki/Build-python-poppler-qt5).

Feel free to add an Ubuntu section in the wiki. I guess the only difference is the names of the packages.

**Comment by DWW256** [comment]
All right, I'm going to try taking a bit more of a look at this now.  I'm not sure what "setup.py" is, but my system can't seem to find it.  I think(?) I installed all the equivalent packages on neon though.

**Comment by fedelibre** [comment]
setup.py is in the source repository. I gave it for granted... Now I've added this to the wiki page:

Clone the repository and enter the directory:

```
git clone git@github.com:frescobaldi/python-poppler-qt5.git
cd python-poppler-qt5
```

before starting the build

**Comment by DWW256** [comment]
Ah.  Now it is giving
```
running build
running build_ext
building 'popplerqt5' extension
/usr/bin/sip -I /usr/share/sip -t POPPLER_V0_85_0 -c build/temp.linux-x86_64-3.8 -b build/temp.linux-x86_64-3.8/poppler-qt5.sbf -I /usr/share/sip/PyQt5 -n PyQt5.sip -t Qt_5_15_0 -t WS_X11 poppler-qt5.sip
sip: Unable to find file "QtCore/QtCoremod.sip"
error: command '/usr/bin/sip' failed with exit status 1
```
Clearly I know nothing about python, heh.

**Comment by fedelibre** [comment]
You may miss some dependency. I've now added instructions for Ubuntu in the wiki.
Try running this command:

    sudo apt install libpoppler-qt5-dev python3-sip-dev python3-pyqt5 qtbase5-dev pyqt5-dev

and see how far you get.

I'm testing the build in an Ubuntu 20.04 container and I'm getting this error:

```
building 'popplerqt5' extension
Can't determine version of poppler-qt5
/usr/bin/sip -I /usr/share/sip -t POPPLER_V0_20_0 -c build/temp.linux-x86_64-3.8 -b build/temp.linux-x86_64-3.8/poppler-qt5.sbf -I /usr/share/sip/PyQt5 -n sip -t WS_X11 -t Qt_5_12_4 poppler-qt5.sip
sip: Poppler::LinkRendition is undefined
error: command '/usr/bin/sip' failed with exit status 1
```

It seems similar to [issue 27 in python-poppler-qt5](https://github.com/frescobaldi/python-poppler-qt5/issues/27).
