### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

### ISSUE THREAD

**Issue by xiebruce** [frescobaldi/frescobaldi#1406]
Frescobaldi: 3.1.3
Extension API: 0.9.0
Python: 3.9.1
python-ly: 0.9.7
Qt: 5.11.3
PyQt: 5.15.2
sip: 4.19.24
poppler: 20.12.1
python-poppler-qt: 0.75.0
OS: macOS-10.16-x86_64-i386-64bit
installation kind: standalone .app bundle

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 141, in engraveRunner
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 145, in engravePreview
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 200, in engrave
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 252, in runJob
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/job/manager.py", line 61, in start_job
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/job/__init__.py", line 211, in start
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/job/lilypond.py", line 176, in configure_command
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/lilypondinfo.py", line 138, in wait
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 253, in start
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 261, in checkstart
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 253, in start
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 264, in checkstart
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 278, in run
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 189, in set
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/signals.py", line 191, in emit
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/signals.py", line 308, in call
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 264, in checkstart
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 276, in run
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/lilypondinfo.py", line 306, in frommacports
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

Optionally describe below what you were doing:

Wrote very simple code 
![image](https://user-images.githubusercontent.com/13575500/144745776-9d38acd6-69a8-476b-8475-983a68d442eb.png)

And click Lilypond→Engrave(Preview)
![image](https://user-images.githubusercontent.com/13575500/144745779-3f6619fe-6a19-4d02-a579-43875d7407f6.png)

Then the error occured
![image](https://user-images.githubusercontent.com/13575500/144745785-26c70e8f-9bc1-4150-925f-c5a20bac5372.png)

macOS version: BigSur 11.5.1

**Comment by cnicolai** [comment]
Hi,

I had the same problem. You can solve it by specifying the full path to lilypond under `Settings/Lilypond`. In the list on that page, you should see an entry for lilypond. Replace the command `lilypond` with `/usr/local/bin/lilypond` (or whatever your path to lilypond is).

This might already work for you. I got an error with ghostscript next, and fixed them by following these steps

```bash
cd /Applications/Frescobaldi.app/Contents/Resources/lib/python3.9
curl https://patch-diff.githubusercontent.com/raw/frescobaldi/frescobaldi/pull/1397.patch | patch -s -p1
```

that I found [here](https://github.com/frescobaldi/frescobaldi/issues/1356).

**Comment by xiebruce** [comment]
> 

Good answer, I'm got exactly the same error as you, including the `gs`(ghostscript), and I've solved it by using your solution, thank you so much!

**Comment by cnicolai** [comment]
No worries, have fun :-)
