### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QApplication has been deleted

### ISSUE THREAD

**Issue by jeanas** [frescobaldi/frescobaldi#1411]
I am intermittently getting the error above on shutdown. Here is a full traceback:

```
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 339, in _error
    self.error_message(error)
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 393, in error_message
    elif self._process.state() == QProcess.NotRunning:
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/app.py", line 237, in excepthook
    if QThread.currentThread() == qApp.thread():
RuntimeError: wrapped C/C++ object of type QApplication has been deleted

Original exception was:
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 339, in _error
    self.error_message(error)
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 393, in error_message
    elif self._process.state() == QProcess.NotRunning:
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 335, in _finished
    self._bye(success)
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 347, in _bye
    self.error = self._process.error()
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/app.py", line 237, in excepthook
    if QThread.currentThread() == qApp.thread():
RuntimeError: wrapped C/C++ object of type QApplication has been deleted

Original exception was:
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 335, in _finished
    self._bye(success)
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 347, in _bye
    self.error = self._process.error()
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
```

I was never able to identify a particular cause.

**Comment by fedelibre** [comment]
I cannot reproduce it on Frescobaldi flatpak package.
Can you paste the versions in *Help>About Frescobaldi>Versions*? Mine are:

```
Frescobaldi: 3.1.3
Extension API: 0.9.0
Python: 3.8.12
python-ly: 0.9.7
Qt: 5.15.3
PyQt: 5.15.2
sip: 4.19.24
poppler: 21.6.1
python-poppler-qt: 0.75.0
OS: Linux-5.15.12-200.fc35.x86_64-x86_64-with-glibc2.2.5
```

**Comment by Jean-Abou-Samra** [comment]
I cannot reproduce it very often either :-(  I'll try to pay more attention to notice if it occurs after closing in some special situations.

My versions are:

```
Frescobaldi: 3.1.3
Extension API: 0.9.0
Python: 3.9.7
python-ly: 0.9.7
Qt: 5.15.2
PyQt: 5.15.4
sip: 6.1.0.dev2104271705
poppler: 21.6.1
python-poppler-qt: 0.75.0
OS: Linux-5.13.0-23-generic-x86_64-with-glibc2.34
```

**Comment by Jean-Abou-Samra** [comment]
I now have a reproducer for this issue. Compile a huge file such as

```
\repeat unfold 1000000 { c' }
```

and while LilyPond is running, quit the application with Ctrl-Q. You are prompted to save the file or not -- select Don't save -- then to abort the job or cancel. Select the option to abort, and on exit Frescobaldi gives exceptions such as

```
  File "/usr/share/frescobaldi/frescobaldi_app/musicpos.py", line 77, in slotTimeout
    d = view.document()
RuntimeError: wrapped C/C++ object of type View has been deleted
```
```
QProcess: Destroyed while process ("/home/jean/repos/lilypond/out/bin/lilypond") is still running.
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 339, in _error
    self.error_message(error)
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 393, in error_message
    elif self._process.state() == QProcess.NotRunning:
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/app.py", line 237, in excepthook
    if QThread.currentThread() == qApp.thread():
RuntimeError: wrapped C/C++ object of type QApplication has been deleted

Original exception was:
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 339, in _error
    self.error_message(error)
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 393, in error_message
    elif self._process.state() == QProcess.NotRunning:
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 335, in _finished
    self._bye(success)
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 347, in _bye
    self.error = self._process.error()
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/app.py", line 237, in excepthook
    if QThread.currentThread() == qApp.thread():
RuntimeError: wrapped C/C++ object of type QApplication has been deleted

Original exception was:
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 335, in _finished
    self._bye(success)
  File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 347, in _bye
    self.error = self._process.error()
RuntimeError: wrapped C/C++ object of type QProcess has been deleted
```

**Comment by fedelibre** [comment]
Probably fixed by #1935

**Comment by bmjcode** [comment]
All these "wrapped object has been deleted" errors share the same root cause. When a window is closed, Qt automatically deletes its associated C++ object, but its Python counterpart remains until it is garbage-collected. There are several different places where it's actually triggered though. #1942 fixes the one in `musicpos.py`, which is caused by a QTimer firing after the window is closed. I'm curious about the one involving QProcess since I don't recall seeing that one before.
