### ISSUE TITLE
TypeError: arguments did not match any overloaded  call: insert(self, str, str)

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#1419]
Reported by a user:

```
Frescobaldi: 3.1.3
Extension API: 0.9.0
Python: 3.9.2
python-ly: 0.9.6
Qt: 5.15.2
PyQt: 5.15.2
sip: 5.4.0
poppler: 20.9.0
python-poppler-qt: 0.75.0
OS: Linux-5.10.0-11-amd64-x86_64-with-glibc2.31

Traceback (most recent call last):
File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 
145, in engravePreview
self.engrave('preview')
File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 
200, in engrave
self.runJob(job_class(doc, args), doc)
File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 
252, in runJob
job.manager.manager(document).start_job(j)
File "/usr/share/frescobaldi/frescobaldi_app/job/manager.py", line 61, 
in start_job
job.start()
File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 225, 
in start
self._update_process_environment()
File "/usr/share/frescobaldi/frescobaldi_app/job/__init__.py", line 304, 
in _update_process_environment
se.remove(k) if v is None else se.insert(k, v)
TypeError: arguments did not match any overloaded call:
insert(self, str, str): argument 2 has unexpected type 'bool'
insert(self, QProcessEnvironment): argument 1 has unexpected type 'str'
```
Running a clean install.

**Comment by wbsoft** [comment]
It's not yet clear to me how this can occur, the only problem I see is that a dict is use as a default argument at `job/__init__.py` which can be edited later. This is dangerous because the default value is then changed :-) for successive calls.

But even then, how can come a Boolean value in one of `self.environment`'s values?

**Comment by dliessi** [comment]
Reported again as #1430.

**Comment by ratnay** [comment]
Any stepwise procedure on fixing this? sorry i'm new to this &  confused.

**Comment by dliessi** [comment]
@ratnay You can try manually applying the changes in 67a2aef6a66fadf3e36bcd7a49d9964fdb38311a and test whether the problem disappears or not (please let us know in both cases).

**Comment by ratnay** [comment]
Where can i find _init_.py via terminal to manually apply those changes?
<img width="444" alt="srh" src="https://user-images.githubusercontent.com/75343865/162636515-ec8b251a-f97c-4536-b7eb-eca9cf4c100f.png">

**Comment by dliessi** [comment]
I don't remember the exact directory structure and I cannot check right now, but you can use `find . -type d -name 'job'` there to find the directory (there are many files named `__init__.py`, so finding the filename directly wouldn't help much).

**Comment by ratnay** [comment]
It worked ( https://github.com/frescobaldi/frescobaldi/commit/67a2aef6a66fadf3e36bcd7a49d9964fdb38311a )thanks

**Comment by dmitry-kabanov** [comment]
I get exactly the same error on macOS Monterey.

Interestingly, when I start from terminal using

    open -a /Applications/Frescobaldi.app

then everything works :-)

**Comment by janekj2727** [comment]
I have exactly the same problem on Ubuntu 22.04. (Changes from [67a2aef](https://github.com/frescobaldi/frescobaldi/commit/67a2aef6a66fadf3e36bcd7a49d9964fdb38311a) already present in frescobaldi-3.2 and the problem persists.) Occurring when trying to engrave the score.
Python 3.10.4
python-ly 0.9.7
PyQt 5.15.6
Qt 5.15.3
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/frescobaldi_app/engrave/__init__.py", line 149, in engravePublish
    self.engrave('publish')
  File "/usr/local/lib/python3.10/dist-packages/frescobaldi_app/engrave/__init__.py", line 200, in engrave
    self.runJob(job_class(doc, args), doc)
  File "/usr/local/lib/python3.10/dist-packages/frescobaldi_app/engrave/__init__.py", line 252, in runJob
    job.manager.manager(document).start_job(j)
  File "/usr/local/lib/python3.10/dist-packages/frescobaldi_app/job/manager.py", line 61, in start_job
    job.start()
  File "/usr/local/lib/python3.10/dist-packages/frescobaldi_app/job/__init__.py", line 225, in start
    self._update_process_environment()
  File "/usr/local/lib/python3.10/dist-packages/frescobaldi_app/job/__init__.py", line 304, in _update_process_environment
    se.remove(k) if v is None else se.insert(k, v)
TypeError: arguments did not match any overloaded call:
  insert(self, str, str): argument 2 has unexpected type 'bool'
  insert(self, QProcessEnvironment): argument 1 has unexpected type 'str'
```
