### ISSUE TITLE
error on opening Frescobaldi

### ISSUE THREAD

**Issue by FrViPofm** [frescobaldi/frescobaldi#1433]
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/highlight.py", line 209, in paintEvent
    super().paintEvent(ev)  # first paint the contents
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/shadow.py", line 43, in paintEvent
    rect = ev.rect().adjusted(-width, -width, width / 2, width / 2)
TypeError: adjusted(self, int, int, int, int): argument 1 has unexpected type 'float'

On Ubuntu 22.04
Frecobaldi installed from synaptic : 3.1.3

Thanks for your precious work !

**Comment by fedelibre** [comment]
I think you should wait for Ubuntu packagers to update to Frescobaldi 3.2.

**Comment by maxiestudies** [comment]
I'm on Debian testing and see the same error
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/highlight.py", line 209, in paintEvent
    super().paintEvent(ev)  # first paint the contents
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/shadow.py", line 43, in paintEvent
    rect = ev.rect().adjusted(-width, -width, width / 2, width / 2)
TypeError: adjusted(self, int, int, int, int)

Version: frescobaldi/testing,now 3.1.3+ds1-1 all [installed]
Debian 11.2.0-20

**Comment by MJE10** [comment]
Confirming the same error on opening the program on Ubuntu 22.04:

Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/highlight.py", line 209, in paintEvent
    super().paintEvent(ev)  # first paint the contents
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/shadow.py", line 43, in paintEvent
    rect = ev.rect().adjusted(-width, -width, width / 2, width / 2)
TypeError: adjusted(self, int, int, int, int): argument 1 has unexpected type 'float'

And a similar error when rendering any music:

 Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 145, in engravePreview
    self.engrave('preview')
  File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 200, in engrave
    self.runJob(job_class(doc, args), doc)
  File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 252, in runJob
    job.manager.manager(document).start_job(j)
  File "/usr/share/frescobaldi/frescobaldi_app/job/manager.py", line 63, in start_job
    app.jobStarted(self.document(), job)
  File "/usr/share/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/usr/share/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
  File "/usr/share/frescobaldi/frescobaldi_app/progress.py", line 73, in jobStarted
    self.showProgress(document)
  File "/usr/share/frescobaldi/frescobaldi_app/progress.py", line 59, in showProgress
    self._bar.start(buildtime, j.elapsed_time())
  File "/usr/share/frescobaldi/frescobaldi_app/widgets/progressbar.py", line 74, in start
    self._timeline.setDuration(total * 1000)
TypeError: setDuration(self, int): argument 1 has unexpected type 'float'

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

Frescobaldi 3.1.3

**Comment by yaemmanuelli** [comment]
Hello @maxiestudies, @fedelibre,

Ubuntu does not support the packaging of Frescobaldi, and sources it from Debian.
Does Debian support this packaging ?
    If yes, when can we expect for a working version de the deb package to be available ?
    If no, who should build Frescobaldi deb package ?
I tried executing Frescobaldi from source, but it complained that qpageview was not found.
Thanks for your help :-)
Regards.
Yves-Antoine Emmanuelli.

**Comment by fedelibre** [comment]
> I tried executing Frescobaldi from source, but it complained that qpageview was not found.

`pip install --user qpageview`

**Comment by fedelibre** [comment]
Debian [has version 3.2 in testing](https://packages.debian.org/search?keywords=frescobaldi).
Ubuntu in [kinetic](https://packages.ubuntu.com/search?keywords=frescobaldi).

You may learn how to install a package from different repositories... In Debian it's called package pinning IIRC.

**Comment by yaemmanuelli** [comment]
@fedelibre,
Sorry I did not have the idea to check Frescobaldi version in Kinetik.
Installing python3.qpageview, then frescobaldi kinetik packages with gdebi solved the issue.
Thanks!

**Comment by oba-reliatec** [comment]
Probably some users of Frescobaldi are more fluent with music and less with source code.
So here is how to apply the [fix provided by Jorma Louhi](https://groups.google.com/g/frescobaldi/c/XkzX4VD-Ku4/m/McDwaIrxAAAJ) on an Ubuntu 22.4 system.
Download the files from into a folder of your choice. In this example I chose Downloads/frescobaldi-fix in the home directory.
Open a terminal (Ctrl-Alt-T) and enter the following commands
```
cd ~/Downloads/frescobaldi-fix
DEST=/usr/share/frescobaldi/frescobaldi_app
sudo cp browser.py $DEST/docbrowser/
sudo cp poppler.py $DEST/qpageview/
sudo cp render.py $DEST/qpageview/
sudo cp scrollarea.py $DEST/qpageview/
sudo cp shadow.py $DEST/qpageview/
sudo cp viewmanager.py $DEST/qpageview/
```
`DEST` is the path where frescobaldi is installed by the package manager on the Ubuntu system, and has to be adjusted in case it is installed elsewhere on your system.
It seems that there are some more places where the type error occurs (error messages can be ignored until the Ubuntu packaging team provides a fixed version hopefully soon). However, after applying this patches Frescobaldi 3.1.3 is usable again on Ubuntu 22.4.1 Jammy Jellyfish.

**Comment by pihentagy** [comment]
> Temporary fix, the issue is not present if you use the Flatpak version of Frescobaldi @maxiestudies

Do i need to download 0.5 Gb of kde to run frescobaldi??

```
~ ⌚ 11:09:51
$ flatpak install frescobaldi
Looking for matches…
Found ref ‘app/org.frescobaldi.Frescobaldi/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: y
Required runtime for org.frescobaldi.Frescobaldi/x86_64/stable (runtime/org.kde.Platform/x86_64/5.15-21.08) found in remote flathub
Do you want to install it? [Y/n]: y

org.frescobaldi.Frescobaldi permissions:
    ipc           network               pulseaudio            x11
    devices       file access [1]       dbus access [2]

    [1] xdg-config/kdeglobals:ro, xdg-documents, xdg-download, xdg-music
    [2] com.canonical.AppMenu.Registrar, org.kde.KGlobalSettings,
        org.kde.kconfig.notify


        ID                                 Branch     Op Remote  Download
 1.     org.frescobaldi.Frescobaldi.Locale stable     i  flathub  < 55.9 MB (partial)
 2.     org.kde.Platform.Locale            5.15-21.08 i  flathub < 346.2 MB (partial)
 3.     org.kde.Platform                   5.15-21.08 i  flathub < 312.1 MB
 4.     org.frescobaldi.Frescobaldi        stable     i  flathub < 136.6 MB

Proceed with these changes to the system installation? [Y/n]: n
```
