### ISSUE TITLE
Ctrl+F causes error loop. AttributeError: 'QChildEvent' object has no attribute 'type'

### ISSUE THREAD

**Issue by felf** [frescobaldi/frescobaldi#1449]
MIME-Version: 1.0

Frescobaldi: 3.2
Extension API: 0.9.0
Python: 3.10.5
python-ly: 0.9.7
Qt: 5.15.4
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.6.0
python-poppler-qt: 21.3.0
OS: Linux-5.18.16-arch1-1-x86_64-with-glibc2.36

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/plugin.py", line 79, in instance
    return _instances[cls][obj]
  File "/usr/lib/python3.10/weakref.py", line 416, in __getitem__
    return self.data[ref(key)]
KeyError: <weakref at 0x7f7ab8182f20; to 'sip.wrappertype' at 0x55efd7d08f60 (Search)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/search/__init__.py", line 364, in event
    elif ev.type() == QEvent.KeyPress:
AttributeError: 'QChildEvent' object has no attribute 'type'

I pressed Ctrl+F to search in a Lilypond file. This happened reproducibly in one particular file, in others sometimes and in some not at all. Also, the error is stuck in a loop; when I close its message window, another opens up.

When trying to narrow the cause down to perhaps a specific line in the file, it started being less than 100 % reproducible. :(
I can provide the file, if needed.

**Comment by jbfavre** [comment]
Hello,
I have the exact same issue with `frescobaldi` 3.2 on Debian sid.
As for you, issue is not reliably reproductible.
Found no solution so far.

**Comment by jcsalomon** [comment]
Same issue, different system (Xubuntu 22.10 using the 3.2 flatpak):

Frescobaldi: 3.2
Extension API: 0.9.0
Python: 3.10.7
python-ly: 0.9.7
Qt: 5.15.6
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.2.0
python-poppler-qt: 21.3.0
OS: Linux-5.19.0-23-generic-x86_64-with-glibc2.36

```
Traceback (most recent call last):
File "/home/chesky/.local/lib/python3.10/site-packages/frescobaldi_app/plugin.py", line 79, in instance
return _instances[cls][obj]
File "/usr/lib/python3.10/weakref.py", line 416, in __getitem__
return self.data[ref(key)]
KeyError:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/chesky/.local/lib/python3.10/site-packages/frescobaldi_app/search/__init__.py", line 364, in event
elif ev.type() == QEvent.KeyPress:
AttributeError: 'QChildEvent' object has no attribute 'type'
```

**Comment by fedelibre** [comment]
> Same issue, different system (Xubuntu 22.10 using the 3.2 flatpak):
> 
> Frescobaldi: 3.2 Extension API: 0.9.0 Python: 3.10.7 python-ly: 0.9.7 Qt: 5.15.6 PyQt: 5.15.7 sip: 6.6.2 qpageview: 0.6.2 poppler: 22.2.0 python-poppler-qt: 21.3.0 OS: Linux-5.19.0-23-generic-x86_64-with-glibc2.36
> 
> ```
> Traceback (most recent call last):
> File "/home/chesky/.local/lib/python3.10/site-packages/frescobaldi_app/plugin.py", line 79, in instance
> return _instances[cls][obj]
> File "/usr/lib/python3.10/weakref.py", line 416, in __getitem__
> return self.data[ref(key)]
> KeyError:
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/chesky/.local/lib/python3.10/site-packages/frescobaldi_app/search/__init__.py", line 364, in event
> elif ev.type() == QEvent.KeyPress:
> AttributeError: 'QChildEvent' object has no attribute 'type'
> ```

You are not using Frescobaldi flatpak here.
It seems you installed Frescobaldi from source in your home.

**Comment by fedelibre** [comment]
> I pressed Ctrl+F to search in a Lilypond file. This happened reproducibly in one particular file, in others sometimes and in some not at all. Also, the error is stuck in a loop; when I close its message window, another opens up.
> 
> When trying to narrow the cause down to perhaps a specific line in the file, it started being less than 100 % reproducible. :( I can provide the file, if needed.

Please provide the file here if you can share it publicly.

**Comment by dliessi** [comment]
A user reported the same error with the comment

> Was using converted part from Musescore xml to onvestigate Lilypond.

> Frescobaldi: 3.2
> Extension API: 0.9.0
> Python: 3.10.10
> python-ly: 0.9.7
> Qt: 5.15.8
> PyQt: 5.15.9
> sip: 6.7.6
> qpageview: 0.6.2
> poppler: 22.6.0
> python-poppler-qt: 21.3.0
> OS: Linux-5.15.108-1-MANJARO-x86_64-with-glibc2.37

**Comment by dliessi** [comment]
Another user reported the same error triggered by Ctrl-H (replace).

```
Frescobaldi: 3.2

Extension API: 0.9.0
Python: 3.10.7
python-ly: 0.9.7
Qt: 5.15.6
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.2.0
python-poppler-qt: 21.3.0
OS: Linux-6.3.7-surface-x86_64-with-glibc2.36
```

**Comment by dliessi** [comment]
I should add that I too get the same error with Frescobaldi 3.2, but not with 3.3. Maybe it was solved by 081cb217763f3d09e6f458bcdc639493eb8ecfde.
