### ISSUE TITLE
Startup error on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by andrewbernard** [frescobaldi/frescobaldi#1455]
Frescobaldi installed from apt repo produces the following error:

Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/highlight.py", line 209, in paintEvent
    super().paintEvent(ev)  # first paint the contents
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/shadow.py", line 43, in paintEvent
    rect = ev.rect().adjusted(-width, -width, width / 2, width / 2)
TypeError: adjusted(self, int, int, int, int): argument 1 has unexpected type 'float'

**Comment by andrewbernard** [comment]
I see this is a duplicate.
