### ISSUE TITLE
Installing frescobaldi in a virtual environment

### ISSUE THREAD

**Issue by nvictor** [frescobaldi/frescobaldi#1456]
Hello all,

I ran into this issue running `frescobaldi 3.1.3` on my Linux machine (Pop_OS / Ubuntu 22.04 / Jammy)

```bash
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/highlight.py", line 209, in paintEvent
    super().paintEvent(ev)  # first paint the contents
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/shadow.py", line 43, in paintEvent
    rect = ev.rect().adjusted(-width, -width, width / 2, width / 2)
TypeError: adjusted(self, int, int, int, int): argument 1 has unexpected type 'float'
```

After looking through the issues, releases, comments, I decided to contact the Ubuntu package maintainers [here](https://answers.launchpad.net/ubuntu/+source/frescobaldi/+question/703228)

Sounds like `frescobaldi 3.2` is not going to be released for Jammy. So I decided to install `frescobaldi` using a virtual environment. But I am unable to install `python-poppler-qt5`.

I am getting this error:

```bash
Collecting python-poppler-qt5
  Using cached python-poppler-qt5-21.3.0.tar.gz (28 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/home/victor/Projects/frescobaldi/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/victor/Projects/frescobaldi/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/victor/Projects/frescobaldi/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/victor/Projects/frescobaldi/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-wirphmzs/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/tmp/pip-build-env-wirphmzs/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-wirphmzs/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 584, in setup
          self.apply_user_defaults(tool)
        File "/tmp/pip-build-env-wirphmzs/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-wirphmzs/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-wirphmzs/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I was wondering if anyone who has been successful at installing `frescobaldi` in a virtual environment can share a mininum `requirements.txt` file?

Thank you.

**Comment by nvictor** [comment]
I tried upgrading pip. I will look into Flatpak. Thank you!

**Comment by nvictor** [comment]
OMG @Jean-Abou-Samra The Flatpak worked!
