### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type TabBar has been deleted

### ISSUE THREAD

**Issue by jeanas** [frescobaldi/frescobaldi#1467]
A user encountered this error while importing a MusicXML file (https://lists.gnu.org/archive/html/lilypond-user-fr/2022-11/msg00016.html).

```
 Traceback (most recent call last):
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/macosx/file_open_eventhandler.py", line 58, in eventFilter
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/macosx/file_open_eventhandler.py", line 50, in openUrl
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/mainwindow.py", line 418, in openUrl
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/mainwindow.py", line 442, in openUrls
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/app.py", line 106, in openUrl
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/document.py", line 242, in new_from_url
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/document.py", line 87, in new_from_url
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/document.py", line 252, in __init__
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/signals.py", line 191, in emit
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/signals.py", line 308, in call
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/tabbar.py", line 128, in addDocument
RuntimeError: wrapped C/C++ object of type TabBar has been deleted
```

**Comment by PeterBjuhr** [comment]
Looks like a broken QT installation, or what do you think?

**Comment by dliessi** [comment]
Another user report on a variation of this issue:

> Frescobaldi: 3.1.3
> Extension API: 0.9.0
> Python: 3.9.1
> python-ly: 0.9.7
> Qt: 5.11.3
> PyQt: 5.15.2
> sip: 4.19.24
> poppler: 20.12.1
> python-poppler-qt: 0.75.0
> OS: macOS-10.14.6-x86_64-i386-64bit
> installation kind: standalone .app bundle

```
Traceback (most recent call last):
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/macosx/globalmenu.py", line 196, in slot_file_open_recent_action
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/mainwindow.py", line 418, in openUrl
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/mainwindow.py", line 442, in openUrls
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/app.py", line 106, in openUrl
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/document.py", line 242, in new_from_url
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/document.py", line 87, in new_from_url
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/document.py", line 252, in __init__
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/signals.py", line 191, in emit
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/signals.py", line 308, in call
File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/tabbar.py", line 128, in addDocument
RuntimeError: wrapped C/C++ object of type TabBar has been deleted
```

**Comment by fedelibre** [comment]
Another user reported this error and said:

> This happened when I started a new session and attempted to load an previous file.

**Comment by fedelibre** [comment]
Given the number of reports we receive, I'm trying to reproduce this error on current stable Frescobaldi (curious to know if it's still present in the Qt6 port), but I'm not able to do it.

@jeanas Do you remember the exact instructions to reproduce it? I'm playing with `Window>New Window` and while I see some defects (e.g. the source file changed in one window is also updated in the other window, which is good; BUT the music in the PDF viewer is not updated in the other window) I cannot trigger the RuntimeError.

**Comment by jeanas** [comment]
Sorry, I don't remember this more closely than what I wrote in the previous comment, and the error didn't reoccur afterwards.Le 23 sept. 2024 à 23:26, Federico Bruni ***@***.***> a écrit :﻿
Given the number of reports we receive, I'm trying to reproduce this error on current stable Frescobaldi (curious to know if it's still present in the Qt6 port), but I'm not able to do it.
@jeanas Do you remember the exact instructions to reproduce it? I'm playing with Window>New Window and while I see some defects (e.g. the source file changed in one window is also updated in the other window, which is good; BUT the music in the PDF viewer is not updated in the other window) I cannot trigger the RuntimeError.

**Comment by bmjcode** [comment]
I don't know if this is related, but I got lots of odd Qt errors trying to use PyQt5 from `pip` on Linux. This was a while back, so my memory is a bit hazy on specifics -- I don't even remember if it crashed on startup or worked for a while until it didn't. What I do remember is *why* it crashed: The binary package on `pip` included its own copy of Qt, which was ABI-incompatible with the system library python-poppler-qt5 was linked to (since I had to build that one from source).

If that's the problem here, the Qt 6 port should fix it because it only touches Qt through PyQt6. Both my Windows and Linux machines are in fact running PyQt6 from `pip`.

**Comment by fedelibre** [comment]
Now we have a new report of a user which runs version 4.0.1. The Qt6 port does not help.
It seems this happens much more frequently on macOS? Or maybe most Frescobaldi users run macOS?

We should find a way to stop these duplicate reports. I guess that GitHub has some tools to prevent duplication. I will have a look tonight.

**Comment by bmjcode** [comment]
Here's an interesting bit from [Qt's layout management documentation](https://doc.qt.io/qt-6/layout.html#tips-for-using-layouts):

> When you use a layout, you do not need to pass a parent when constructing the child widgets. The layout will automatically reparent the widgets (using [QWidget::setParent](https://doc.qt.io/qt-6/qwidget.html#setParent)()) so that they are children of the widget on which the layout is installed.

Now look at this block from our [`MainWindow.__init__()`](https://github.com/frescobaldi/frescobaldi/blob/7feca8b73cf9ebbf357854a8fb801b81bd2ad213/frescobaldi/mainwindow.py#L129):

```python
        mainwidget = QWidget()
        self.setCentralWidget(mainwidget)
        layout = QVBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        mainwidget.setLayout(layout)
        self.tabBar = tabbar.TabBar(self)
        self.viewManager = viewmanager.ViewManager(self)
        layout.addWidget(self.tabBar)
        layout.addWidget(self.viewManager)
```

The tab bar and view manager are created with the `MainWindow` instance as their parent, but are reparented to `mainwidget` when added to the layout. And since `mainwidget` is a local variable, it is presumably garbage-collected when `__init__()` returns, taking its new children with it. I think this may be the source of our problem.

**Comment by fedelibre** [comment]
Well,  if you fix this bug you deserve a beer for each duplicate issue :-)

**Comment by fedelibre** [comment]
Hopefully fixed in version 4.0.2 by #1935  

If it's not fixed, I'm sure we'll receive new reports.

**Comment by bmjcode** [comment]
That reproduces it on mine too. Looking into this now.

**Comment by bmjcode** [comment]
Turns out there were two slightly different problems there, but they're variations on the same theme. Basically Qt is deleting C++ objects but not telling our Python code they're gone. #1942 fixes both on mine.

**Comment by fedelibre** [comment]
Fixed by #1942
