### ISSUE TITLE
"Force use of the tools’ #! lines" needs to be on in order to let Frescobaldi recognize convert-ly in LilyPond 2.24

### ISSUE THREAD

**Issue by JunTamura1959** [frescobaldi/frescobaldi#1492]
"Force use of the tools’ #! lines" in the "Tool Commands" tab in the Edit dialog for the "LilyPond version to use" in the "LilyPond Preferences" needs to be checked on in order to get LilyPond 2.24 appeared in the pull down menu in the Convert-ly dialog. I'm not sure whether this is expected behavior or not. I found this on macOS Monterey 12.6.2 with Frescobaldi 3.2 installed with MacPorts and "official" lilypond-2.24.0-darwin-x86_64.tar.gz binaries.

**Comment by fedelibre** [comment]
This option is specific of Mac. I guess it should be added to the docs

**Comment by dliessi** [comment]
Maybe the option should be enabled by default or maybe it should even not be an option and be always enabled.

@fedelibre @jeanas do you see any adverse effect to always respect the #! line of LilyPond's Python tools, at least for recent versions of LilyPond? Everything works for MacPorts's LilyPond, but I recall that the Python interpreter included in the official compiled LilyPond in the past lacked some modules used by the scripts. Maybe now this is fixed, but I cannot test it since my macOS is too old.

@JunTamura1959 Does convert-ly work for you from within Frescobaldi when the option is active? Could you please test also importing MIDI, MusicXML and ABC files?

**Comment by JunTamura1959** [comment]
Hello,

I tried ABC2ly and it worked from Frescobaldi’s view point, I think.

I tried to import
https://www.ucolick.org/~sla/abcmusic/s7m2p.abc￼
s7m2p
142 KB

and I had the following error but this is nothing to do with Frescobaldi but rather some issue on abc2ly.py, I believe.

Starting abc2ly...
abc2ly from LilyPond 2.24.1
Parsing `/Users/tamura/Documents/Private/s7m2p.abc'...
Line ... [100][200][300][400][500][600][700][800][900][1000][1100][1200][1300][1400][1500][1600][1700][1800][1900][2000][2100][2200][2300][2400][2500][2600][2700][2800][2900]lilypond output to: `/var/folders/hf/rq2_kq2j5pj9_zt0hvm57t0m0000gn/T/frescobaldi-n65d6bnl/tmpa60gh8th/s7m2p.ly'...Traceback (most recent call last):
  File "/Users/tamura/lilypond-2.24.1/bin/../libexec/abc2ly", line 1553, in <module>
    dump_voices(outf)
  File "/Users/tamura/lilypond-2.24.1/bin/../libexec/abc2ly", line 312, in dump_voices
    if repeat_state[voice_idx_dict[k]]:
IndexError: list index out of range
Exited with return code 1.
