### ISSUE TITLE
Python type errors

### ISSUE THREAD

**Issue by parekhnish** [frescobaldi/frescobaldi#1493]
(Frescobaldi `3.1.3`, installed using `apt` on Ubuntu `22.04`)

I get the following error when I start Frescobaldi:
```
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/highlight.py", line 209, in paintEvent
    super().paintEvent(ev)  # first paint the contents
  File "/usr/share/frescobaldi/frescobaldi_app/qpageview/shadow.py", line 43, in paintEvent
    rect = ev.rect().adjusted(-width, -width, width / 2, width / 2)
TypeError: adjusted(self, int, int, int, int): argument 1 has unexpected type 'float'
```

I canstill open up `.ly` files, but when I try to engrave them, I then get this error:
```
Traceback (most recent call last):
  File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 141, in engraveRunner
    self.engravePreview()
  File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 145, in engravePreview
    self.engrave('preview')
  File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 200, in engrave
    self.runJob(job_class(doc, args), doc)
  File "/usr/share/frescobaldi/frescobaldi_app/engrave/__init__.py", line 252, in runJob
    job.manager.manager(document).start_job(j)
  File "/usr/share/frescobaldi/frescobaldi_app/job/manager.py", line 63, in start_job
    app.jobStarted(self.document(), job)
  File "/usr/share/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/usr/share/frescobaldi/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
  File "/usr/share/frescobaldi/frescobaldi_app/progress.py", line 73, in jobStarted
    self.showProgress(document)
  File "/usr/share/frescobaldi/frescobaldi_app/progress.py", line 59, in showProgress
    self._bar.start(buildtime, j.elapsed_time())
  File "/usr/share/frescobaldi/frescobaldi_app/widgets/progressbar.py", line 74, in start
    self._timeline.setDuration(total * 1000)
TypeError: setDuration(self, int): argument 1 has unexpected type 'float'
```

I have no idea what's happening, but it seems like all the places where it's expecting `int`s, it is getting `float`s. Again, not sure why! (And why is that even a problem; I assumed type checking isn't as strict in Python!)

If I install Frescobaldi from source, it all works perfectly. Both on the `master` branch, as well on commit dd9b1c667f75c83ef2146769ffe605eb6b824e5e (i.e. the `3.2` release tag), it works. And I CAN reproduce the error if I switch to commit 438f78009c2aa3ded10da11a16483a3720a712cc (i.e. tagged `3.1.3`), so something was fixed between then and this version.

Since Ubuntu `22.04` is an LTS version, I assume a lot of people might be willing to use it, hence bringing up this issue. I've also raised another issue (https://github.com/frescobaldi/frescobaldi/issues/1494) to ask why does it still use `3.1.3`, in case that is a better solution than fixing this.

**Comment by parekhnish** [comment]
Oh, my bad. This has already been discussed in https://github.com/frescobaldi/frescobaldi/issues/1433
