### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type General has been deleted

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#1505]
I got this error while changing Frescobaldi language in the preferences from system language (italian) to english.
It happens again if I change it back to system language:

```
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/frescobaldi_app/signals.py", line 191, in emit
    l.call(args, kwargs)
  File "/app/lib/python3.9/site-packages/frescobaldi_app/signals.py", line 308, in call
    return self.func(obj, *args[self.argslice], **kwargs)
  File "/app/lib/python3.9/site-packages/frescobaldi_app/preferences/general.py", line 146, in translateUI
    self.setTitle(_("General Preferences"))
RuntimeError: wrapped C/C++ object of type General has been deleted
```

This happened on current Frescobaldi flatpak (version 3.2):

```
Frescobaldi: 3.2
Extension API: 0.9.0
Python: 3.9.9
python-ly: 0.9.7
Qt: 5.15.7
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 21.8.0
python-poppler-qt: 21.3.0
OS: Linux-6.1.5-200.fc37.x86_64-x86_64-with-glibc2.33
```

It doesn't happen with Fedora 37 package:

```
Frescobaldi: 3.2
Extension API: 0.9.0
Python: 3.11.1
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.6
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.1.0
python-poppler-qt: 21.3.0
OS: Linux-6.1.5-200.fc37.x86_64-x86_64-with-glibc2.36
```

**Comment by fedelibre** [comment]
After deleting Frescobaldi configuration files in the home (for flatpak it's `~/.var/app/org.frescobaldi.Frescobaldi`), the error cannot be reproduced.
