### ISSUE TITLE
Internal Errors happen constanlty

### ISSUE THREAD

**Issue by KaiVinter** [frescobaldi/frescobaldi#1513]
I just downloaded Frescobaldi (3.1.3) from Homebrew and I have installed the LilyPond Formula (2.24.0) with Homebrew as well.
I'm trying to process a LilyPond file and I'm also trying to import a MusicXML file into Frescobaldi. However, just opening Frescobaldi or trying to import the MusicXML file will cause this errors.

```
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 141, in engraveRunner
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 145, in engravePreview
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 200, in engrave
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/engrave/__init__.py", line 252, in runJob
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/job/manager.py", line 61, in start_job
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/job/__init__.py", line 211, in start
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/job/lilypond.py", line 176, in configure_command
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/lilypondinfo.py", line 138, in wait
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 253, in start
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 261, in checkstart
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 253, in start
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 264, in checkstart
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 278, in run
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 189, in set
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/signals.py", line 191, in emit
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/signals.py", line 308, in call
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 264, in checkstart
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/cachedproperty.py", line 276, in run
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/lilypondinfo.py", line 306, in frommacports
TypeError: unsupported operand type(s) for +: 'bool' and 'str'
```

In case this is important:
I'm using Python 3.11.1 globally with PyEnv, and I'm on MacOS Monterrey 12.6.1

**Comment by KaiVinter** [comment]
Nevermind, I just found #1492.

**Comment by KaiVinter** [comment]
However, it still doesn't seem to work:

```
Starting musicxml2ly...
Python path configuration:
  PYTHONHOME = '/Applications/Frescobaldi.app/Contents/Resources'
  PYTHONPATH = '/Applications/Frescobaldi.app/Contents/Resources'
  program name = '/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/Applications/Frescobaldi.app/Contents/Resources/lib/python3.11'
  sys._base_executable = '/usr/local/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/bin/python3.11'
  sys.base_prefix = '/Applications/Frescobaldi.app/Contents/Resources'
  sys.base_exec_prefix = '/Applications/Frescobaldi.app/Contents/Resources'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/local/Cellar/python@3.11/3.11.1/libexec/bin/python'
  sys.prefix = '/Applications/Frescobaldi.app/Contents/Resources'
  sys.exec_prefix = '/Applications/Frescobaldi.app/Contents/Resources'
  sys.path = [
    '/Applications/Frescobaldi.app/Contents/Resources',
    '/Applications/Frescobaldi.app/Contents/Resources/lib/python311.zip',
    '/Applications/Frescobaldi.app/Contents/Resources/lib/python3.11',
    '/Applications/Frescobaldi.app/Contents/Resources/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000010d219600 (most recent call first):
  <no Python frame>
Exited with return code 1.
```

**Comment by KaiVinter** [comment]
It seems to look for the `/Applications/Frescobaldi.app/Contents/Resources/lib/python3.11/` folder, but that doesn't exist...

**Comment by KaiVinter** [comment]
Another related issue:

I gave up and tried the regular download from lilypond.org and used those in the Downloads folder, but then this showed up:
```
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/file_import/toly_dialog.py", line 140, in about_to_accept
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/file_import/musicxml.py", line 112, in configure_job
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.9/frescobaldi_app/file_import/toly_dialog.py", line 150, in configure_job
AttributeError: 'NoneType' object has no attribute 'toolcommand'
```

**Comment by KaiVinter** [comment]
I tried uninstalling python@3.10 from Homebrew and installing another LilyPond but now from the lilypond.org page, and now the log is this:

```
Starting musicxml2ly...
Python path configuration:
  PYTHONHOME = '/Applications/Frescobaldi.app/Contents/Resources'
  PYTHONPATH = '/Applications/Frescobaldi.app/Contents/Resources'
  program name = '/Users/username/Downloads/lilypond-2.24.0/bin/../libexec/python3.10'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/Users/username/Downloads/lilypond-2.24.0/bin/../libexec/python3.10'
  sys.base_prefix = '/Applications/Frescobaldi.app/Contents/Resources'
  sys.base_exec_prefix = '/Applications/Frescobaldi.app/Contents/Resources'
  sys.platlibdir = 'lib'
  sys.executable = '/Users/username/Downloads/lilypond-2.24.0/bin/../libexec/python3.10'
  sys.prefix = '/Applications/Frescobaldi.app/Contents/Resources'
  sys.exec_prefix = '/Applications/Frescobaldi.app/Contents/Resources'
  sys.path = [
    '/Applications/Frescobaldi.app/Contents/Resources',
    '/Applications/Frescobaldi.app/Contents/Resources/lib/python310.zip',
    '/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10',
    '/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000105744600 (most recent call first):
  <no Python frame>
Exited with return code 1.
```

**Comment by KaiVinter** [comment]
But again, `/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10` and `/Users/username/Downloads/lilypond-2.24.0/bin/../libexec/python3.10` don't exist

**Comment by KaiVinter** [comment]
Okay, I just found out that #1355 was the same problem as three messages above

**Comment by KaiVinter** [comment]
I gave up trying on MacOS and tried a Windows 11 VM with Python 3.10.
This is now the log:
```
Starting pythonw.exe...
musicxml2ly: Reading MusicXML from C:\Users\imac\Documents\LilyPond\boccherinicello.mxl ...
musicxml2ly: Input file C:\Users\imac\Documents\LilyPond\boccherinicello.mxl is compressed, extracting raw MusicXML data
Traceback (most recent call last):
  File "C:\Program Files (x86)\LilyPond\usr\bin\musicxml2ly", line 3479, in <module>
    main()
  File "C:\Program Files (x86)\LilyPond\usr\bin\musicxml2ly", line 3472, in main
    voices = convert(filename, options)
  File "C:\Program Files (x86)\LilyPond\usr\bin\musicxml2ly", line 3333, in convert
    (voices, staff_info) = get_all_voices(parts)
  File "C:\Program Files (x86)\LilyPond\usr\bin\musicxml2ly", line 2910, in get_all_voices
    all_voices = voices_in_part_in_parts(parts)
  File "C:\Program Files (x86)\LilyPond\usr\bin\musicxml2ly", line 2900, in voices_in_part_in_parts
    voices = voices_in_part(p)
  File "C:\Program Files (x86)\LilyPond\usr\bin\musicxml2ly", line 2887, in voices_in_part
    part.extract_voices()
  File "C:\Program Files (x86)\LilyPond\usr\share\lilypond\current\python\musicxml.py", line 1592, in extract_voices
    voices[id].add_element(n)
  File "C:\Program Files (x86)\LilyPond\usr\share\lilypond\current\python\musicxml.py", line 1251, in add_element
    nr = l.get_number()
  File "C:\Program Files (x86)\LilyPond\usr\share\lilypond\current\python\musicxml.py", line 971, in get_number
    return int(self.number)
ValueError: invalid literal for int() with base 10: 'part1verse1'
Exited with return code 1.
```
(Is using musicxml2ly even possible? 😓)

**Comment by KaiVinter** [comment]
I see. I had my suspicions, but I wanted to be sure. I'll try reporting it to LilyPond then. Thank you @Jean-Abou-Samra

**Comment by dliessi** [comment]
https://github.com/frescobaldi/frescobaldi/issues/1513#issuecomment-1416895575 and https://github.com/frescobaldi/frescobaldi/issues/1513#issuecomment-1418254805 are the same as #1395.

**Comment by dliessi** [comment]
> [#1513 (comment)](https://github.com/frescobaldi/frescobaldi/issues/1513#issuecomment-1416895575) and [#1513 (comment)](https://github.com/frescobaldi/frescobaldi/issues/1513#issuecomment-1418254805) are the same as #1395.

#1560 should fix them.

**Comment by dliessi** [comment]
I cannot reproduce https://github.com/frescobaldi/frescobaldi/issues/1513#issuecomment-1417473171 . @KaiVinter can you still reproduce it? Can you provide more details?

**Comment by dliessi** [comment]
I believe that https://github.com/frescobaldi/frescobaldi/issues/1513#issuecomment-1417473171, which is the same as #1355, depends on #1492: reading the relevant code in `file_import/tolydialog.py`, `lilychooser.py`, `lilypondinfo.py` and `macosx/__init__.py` I think that `self._info` is `None` because on recent macOS there is no preinstalled Python, so `system_python` returns `None`.

From our point of view this issue can be closed, but I'm leaving it to @jeanas as there is the possible bug in MusicXML to report to LilyPond.
