### ISSUE TITLE
ImportError: cannot import name 'event' from 'ly.music' (/usr/lib/python3.8/site-packages/ly/music/__init__.py)

### ISSUE THREAD

**Issue by dbitouze** [frescobaldi/frescobaldi#1593]
Traceback (most recent call last):
  File "/home/bitouze/InstallationsLocales/frescobaldi-3.3.0/frescobaldi_app/musicpos.py", line 88, in slotTimeout
    pos = m.time_position(c.position())
  File "/usr/lib/python3.8/site-packages/ly/music/items.py", line 310, in time_position
ImportError: cannot import name 'event' from 'ly.music' (/usr/lib/python3.8/site-packages/ly/music/__init__.py)

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.8.14
python-ly: 0.9.6
Qt: 5.15.2
PyQt: 5.15.2
sip: 4.19.24
qpageview: 0.6.2
poppler: 0.84.0
python-poppler-qt: 0.75.0
OS: Linux-6.1.23-desktop-1.mga8-x86_64-with-glibc2.2.5

**Comment by dbitouze** [comment]
@jeanas Yes, there was such an `event.py` file:
```
$ ls /usr/lib/python3.8/site-packages/ly/music/
event.py  __init__.py  items.py  __pycache__  read.py
```
About, `python-ly`, I installed the latest version. Afterwards, `frescobaldi` seems to work nicely: thanks!
