### ISSUE TITLE
Assertion error at startup after latest pull

### ISSUE THREAD

**Issue by ksnortum** [frescobaldi/frescobaldi#1632]
I usually run Frescobaldi from a git repo with the latest updates, but after I pulled in the changes from the master branch today, Frescobaldi does not launch and prints this traceback:

    Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
    QSocketNotifier: Can only be used with threads started with QThread
    Traceback (most recent call last):
      File "/home/knute/git-repos/frescobaldi/frescobaldi", line 30, in <module>
        main()
      File "/home/knute/git-repos/frescobaldi/frescobaldi_app/__main__.py", line 166, in main
        app.instantiate()               # Construct QApplication object
      File "/home/knute/git-repos/frescobaldi/frescobaldi_app/app.py", line 135, in instantiate
        appInstantiated()
      File "/home/knute/git-repos/frescobaldi/frescobaldi_app/signals.py", line 191, in emit
        l.call(args, kwargs)
      File "/home/knute/git-repos/frescobaldi/frescobaldi_app/signals.py", line 317, in call
        return self.func(*args[self.argslice], **kwargs)
      File "/home/knute/git-repos/frescobaldi/frescobaldi_app/i18n/setup.py", line 100, in _start_up
        _setup()
      File "/home/knute/git-repos/frescobaldi/frescobaldi_app/i18n/setup.py", line 93, in _setup
        install(language)
      File "/home/knute/git-repos/frescobaldi/frescobaldi_app/i18n/__init__.py", line 68, in install
        builtins._ = translator(language or None)
      File "/home/knute/git-repos/frescobaldi/frescobaldi_app/i18n/__init__.py", line 55, in translator
        assert language in available() or language.split('_')[0] in available()
    AssertionError

I launch Frescobaldi like this:

    python3 ~/git-repos/frescobaldi/frescobaldi --python-ly ~/git-repos/python-ly

Version 3.3.0 works fine and gives me this version data, if it's helpfull:

    Frescobaldi: 3.3.0
    Extension API: 0.9.0
    Python: 3.10.6
    python-ly: 0.9.7
    Qt: 5.15.3
    PyQt: 5.15.6
    sip: 6.5.1
    qpageview: 0.6.2
    poppler: 22.2.0
    python-poppler-qt: 0.75.0
    OS: Linux-5.19.0-45-generic-x86_64-with-glibc2.35

I am on Ubuntu 22.04.2.

**Comment by ksnortum** [comment]
When I try the `make` command, I get an error saying that `msgcat` and `msgfmt` can't be found:

    make -C i18n
    make: Entering directory '/home/knute/git-repos/frescobaldi/i18n'
    mkdir -p `dirname ../frescobaldi_app/i18n/cs/LC_MESSAGES/frescobaldi.mo`
    msgcat -o - frescobaldi/cs.po userguide/cs.po | msgfmt -o ../frescobaldi_app/i18n/cs/LC_MESSAGES/frescobaldi.mo -
    /bin/sh: 1: msgcat: not found
    /bin/sh: 1: msgfmt: not found
    make: *** [Makefile:53: ../frescobaldi_app/i18n/cs/LC_MESSAGES/frescobaldi.mo] Error 127
    make: Leaving directory '/home/knute/git-repos/frescobaldi/i18n'

I went to INSTALL.md and did the `apt` command to install the dependencies, but I still got the error.

**Comment by ksnortum** [comment]
I ran `make -C i18n`, `make -C linux`, and installed with `pipx`, but I am still getting the same traceback when I try to launch frescobaldi.  If I look in `frescobaldi/i18n/frescobaldi` I see many po files, but no en.po.

**Comment by ksnortum** [comment]
Thank you for this.
