### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/frescobaldi-qbzx5wv6/tmp5t_xf9z_'

### ISSUE THREAD

**Issue by amca01** [frescobaldi/frescobaldi#1634]
I got this error in a popup box when attempting to run Lilypond on a file from withing Frescobaldi; the box also asked me politely to send the error to github, which is what I've done here.

--

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/engrave/__init__.py", line 146, in engravePreview
    self.engrave('preview')
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/engrave/__init__.py", line 201, in engrave
    self.runJob(job_class(doc, args), doc)
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/job/lilypond.py", line 191, in __init__
    super(PreviewJob, self).__init__(document, args, title)
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/job/lilypond.py", line 96, in __init__
    input, self.includepath = docinfo.jobinfo(True)
  File "/usr/lib/python3.10/site-packages/frescobaldi_app/documentinfo.py", line 220, in jobinfo
    scratch.saveDocument()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/frescobaldi-qbzx5wv6/tmp5t_xf9z_'

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.9
qpageview: 0.6.2
poppler: 22.6.0
python-poppler-qt: 21.3.0
OS: Linux-6.2.12-arch1-1-x86_64-with-glibc2.37

**Comment by fedelibre** [comment]
Bug still present in version 4.0.4 (today we got a report from a macOS user).

Probably the temporary directory has been cleared and Frescobaldi can't find it anymore?
I wonder how this could happen, since the /tmp directory is usually emptied after a system restart and Frescobaldi does not cache a not saved file (only not saved file build files in /tmp). I can only think of the user clearing the /tmp dir maybe...
