### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1013: ordinal not in range(128)

### ISSUE THREAD

**Issue by StanSanderson** [frescobaldi/frescobaldi#1636]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/fonts/__init__.py", line 74, in document_fonts
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/fonts/dialog.py", line 166, in __init__
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/fonts/dialog.py", line 250, in invalidate_command
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/fonts/fontcommand.py", line 514, in invalidate_command
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/fonts/dialog.py", line 260, in show_sample
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1013: ordinal not in range(128)

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.3
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.9.0
python-poppler-qt: 21.3.0
OS: macOS-11.7.8-x86_64-i386-64bit
installation kind: standalone .app bundle

**Comment by fedelibre** [comment]
Closing this issue in favour of the more recent #1729 as it contains information on what triggers the error.
