### ISSUE TITLE
AttributeError: 'LilyPondInfo' object has no attribute 'frommacports'

### ISSUE THREAD

**Issue by brass999** [frescobaldi/frescobaldi#1660]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/engrave/__init__.py", line 142, in engraveRunner
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/engrave/__init__.py", line 146, in engravePreview
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/engrave/__init__.py", line 201, in engrave
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/engrave/__init__.py", line 258, in runJob
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/job/manager.py", line 61, in start_job
AttributeError: 'LilyPondInfo' object has no attribute 'frommacports'

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.3
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.9.0
python-poppler-qt: 21.3.0
OS: macOS-13.5-x86_64-i386-64bit
installation kind: standalone .app bundle

**Comment by brass999** [comment]
Dear Jean,

Thanks for your swift reply.
I will reinstall lilypond and frescobaldi again and will send you the full bug report if I can reproduce the error.

Thanks!

Verstuurd vanaf mijn iPhone

Op 5 aug. 2023 om 18:57 heeft Jean Abou-Samra ***@***.***> het volgende geschreven:

﻿

@brass999<https://github.com/brass999> Can you still reproduce this? If so, could you please paste the whole traceback that you get in the bug reporting window into this issue? (The one that got pasted automatically is truncated due to GitHub limitations.) Thanks.

**Comment by brass999** [comment]
I have already removed it, but I will reinstall it  and try if I can reproduce the error. I am using MacOS and have installed both lilypond and frescobaldi using homebrew, frescobalding using the brew cask. The error seems to be related to the fact that it can’t find the ghostscript program, but this is installed. I will sent you a full detail of my set-up and error log (have to do that this evening). Thanks for your support so far, much appreciated!

Kind regards Leo.

Verstuurd vanaf mijn iPhone

Op 6 aug. 2023 om 22:32 heeft Jean Abou-Samra ***@***.***> het volgende geschreven:

﻿

Well, depends on whether you can still reproduce it... If you can right now, please don't reinstall but send the traceback first. I fear it could go away after reinstalling and you wouldn't be able to reproduce it anymore.

I say this because there is no use or definition of a "frommacports" method anywhere in the code base of Frescobaldi 3.3.0, it's been removed from the code some time before the release, so I'm very confused that this can occur with the 3.3.0 bundle. Which brings me to my next question: how did you install Frescobaldi? Did you simply download the bundle, or did you tinker with it / do weirder stuff?

**Comment by brass999** [comment]
Dear Jean,

Further to your questions, see my additional information on system, installation procedure followed, the versions of lilypond and Frescobaldi, and the error log file running Frescobaldi.

I did not tinker anything.

Hope this is of any help? 


If you have any suggestions for alternative installs, that is appreciated as well. 

I also noticed that more users appears to have the same problem. Seems to be related to the Ghostscript program that is called from within Frescobaldi (actually lilypond)? 


Thanks again in advance for your time, much appreciated!

Kind regards, 
Leo.  

I. System details:

Macbook pro
2.3 GHz 8-core Intel Core i9
AMD Radeon Pro 5500M 4 Gb
Intel UHD Graphics 630 1536 MB
Memory 16 GB 2667 MHz DDR4
Macintosh HD
MacOS Ventura 13.5


II. Installation Lilypond & Frescobaldi

I have installed both using Homebrew as follows:

> brew install lilypond

> brew install —cask frescobaldi

Info version of lilypond (Brew info lily pond):

==> lilypond: stable 2.24.1 (bottled), HEAD
Music engraving system
https://lilypond.org
/usr/local/Cellar/lilypond/2.24.1 (448 files, 28.9MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-08-07 at 12:36:24
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lilypond.rb
License: GPL-3.0-or-later and GPL-3.0-only and OFL-1.1-RFN and GFDL-1.3-no-invariants-or-later and Public Domain and MIT and AGPL-3.0-only and LPPL-1.3c
==> Dependencies
Build: bison, fontforge, gettext, pkg-config, t1utils, texinfo, texlive
Required: fontconfig, freetype, ghostscript, guile, pango, ***@***.***
==> Options
--HEAD
	Install HEAD version
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/lilypond
==> Analytics
install: 173 (30 days), 532 (90 days), 876 (365 days)
install-on-request: 171 (30 days), 523 (90 days), 865 (365 days)
build-error: 0 (30 days)

Brew info provided following information in version of Frescobaldi

==> frescobaldi: 3.3.0
https://frescobaldi.org/
/usr/local/Caskroom/frescobaldi/3.3.0 (3 files, 90.1KB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/frescobaldi.rb
==> Name
Frescobaldi
==> Description
LilyPond editor
==> Artifacts
Frescobaldi.app (App)
==> Analytics
install: 23 (30 days), 105 (90 days), 207 (365 days)


III RUNNING FRESCOBALDI - ERROR LOG

Starting lilypond 2.24.1 [All-of-Me_book-V24.ly]...
Processing `All-of-Me_book-V24.ly'
Parsing...
Interpreting music...[8][16][24][32]
Preprocessing graphical objects...
Interpreting music...[8][16][24][32]
Preprocessing graphical objects...
Interpreting music...[8][16][24][32]
Preprocessing graphical objects...
Interpreting music...[8][16]
Preprocessing graphical objects...
Finding the ideal number of pages...
Fitting music on 1 or 2 pages...
Drawing systems...
Finding the ideal number of pages...
Fitting music on 1 or 2 pages...
Drawing systems...
Finding the ideal number of pages...
Fitting music on 1 or 2 pages...
Drawing systems...
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
Converting to `All-of-Me_book-V24.pdf'...
warning: g_spawn_sync failed (-1): gs: Failed to execute child process “gs” (No such file or directory)
warning: `(gs -q -dNODISPLAY -dNOSAFER -dNOPAUSE -dBATCH -dAutoRotatePages=/None -dPrinted=false /var/folders/pg/f52hd66j46x55dtp2rxn5c8r0000gn/T//lilypond-tmp-7462770)' failed (-1)

fatal error: failed files: "/Users/leodemul/lilypond/All-of-Me_book-V24.ly"
Exited with return code 1.


IV TO CHECK THE .ly file on a linux system to exclude any format errors in my .ly file:

System: Linux Mint
Lilypond: 2.22.1
Frescobaldi 3.2
Both installed using Linux Mint repository (older versions)

This compiled the same .ly file without any problems, see log below: 


Starting lilypond 2.22.1 [All-of-Me_book-V24.ly]...
Processing `All-of-Me_book-V24.ly'
Parsing...
Interpreting music...[8][16][24][32]
Preprocessing graphical objects...
Interpreting music...[8][16][24][32]
Preprocessing graphical objects...
Interpreting music...[8][16][24][32]
Preprocessing graphical objects...
Interpreting music...[8][16]
Preprocessing graphical objects...
Finding the ideal number of pages...
Fitting music on 1 or 2 pages...
Drawing systems...
Finding the ideal number of pages...
Fitting music on 1 or 2 pages...
Drawing systems...
Finding the ideal number of pages...
Fitting music on 1 or 2 pages...
Drawing systems...
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
Converting to `All-of-Me_book-V24.pdf'...
Success: compilation successfully completed
Completed successfully in 2.4".

**Comment by brass999** [comment]
Dear Jean,



Seems to be the same output. Also complaining about ‘gs’ access.



See log below.

Regards,

Leo. 



GNU LilyPond 2.24.1 (running Guile 3.0)

Processing `All-of-Me_book-V24.ly'

Parsing...

Interpreting music...[8][16][24][32]

Preprocessing graphical objects...

Interpreting music...[8][16][24][32]

Preprocessing graphical objects...

Interpreting music...[8][16][24][32]

Preprocessing graphical objects...

Interpreting music...[8][16]

Preprocessing graphical objects...

Finding the ideal number of pages...

Fitting music on 1 or 2 pages...

Drawing systems...

Finding the ideal number of pages...

Fitting music on 1 or 2 pages...

Drawing systems...

Finding the ideal number of pages...

Fitting music on 1 or 2 pages...

Drawing systems...

Finding the ideal number of pages...

Fitting music on 1 page...

Drawing systems...

Converting to `All-of-Me_book-V24.pdf'...

warning: g_spawn_sync failed (-1): gs: Failed to execute child process “gs” (No such file or directory)

warning: `(gs -q -dNODISPLAY -dNOSAFER -dNOPAUSE -dBATCH -dAutoRotatePages=/None -dPrinted=false /var/folders/pg/f52hd66j46x55dtp2rxn5c8r0000gn/T//lilypond-tmp-7624598)' failed (-1)

 

fatal error: failed files: "All-of-Me_book-V24.ly"

**Comment by brass999** [comment]
Dear Jean,

I have removed lilypond and reinstalled it from the official lilypond website and following the instructions at the website. 

I had to provide access to lilypond and gs (system settings/Privacy and Security settings) and after that it works!

Again thanks for your excellent and swift report!

Kind regards,

Leo.
