### ISSUE TITLE
FileNotFoundError: [Errno 2] File or directory not found: '/home/username/lilypond/usr/bin/lilypond'

### ISSUE THREAD

**Issue by dliessi** [frescobaldi/frescobaldi#1678]
A user reports the following error.

```
Frescobaldi: 3.0.0 -- Python: 3.8.10 -- python-ly: 0.9.5 -- Qt: 5.12.8
-- PyQt: 5.14.1 -- sip: 4.19.21 -- poppler: 0.80.0 -- python-poppler-qt:
0.24.2 -- OS: Linux-5.4.0-162-generic-x86_64-with-glibc2.29

Traceback (most recent call last):
File "/usr/share/frescobaldi/frescobaldi_app/preferences/__init__.py",
line 110, in done
self.saveSettings()
File "/usr/share/frescobaldi/frescobaldi_app/preferences/__init__.py",
line 135, in saveSettings
page.saveSettings()
File "/usr/share/frescobaldi/frescobaldi_app/preferences/__init__.py",
line 329, in saveSettings
group.saveSettings()
File "/usr/share/frescobaldi/frescobaldi_app/preferences/lilypond.py",
line 124, in saveSettings
lilypondinfo.saveinfos()
File "/usr/share/frescobaldi/frescobaldi_app/lilypondinfo.py", line 79,
in saveinfos
info.write(s)
File "/usr/share/frescobaldi/frescobaldi_app/lilypondinfo.py", line 375,
in write
settings.setValue("mtime", int(os.path.getmtime(self.abscommand())))
File "/usr/lib/python3.8/genericpath.py", line 55, in getmtime
return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden:
'/home/username/lilypond/usr/bin/lilypond'
```

**Comment by bmjcode** [comment]
Fixed in #2186.
