### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by dliessi** [frescobaldi/frescobaldi#1680]
A user reports the following error.

```
Frescobaldi: 3.1.2
Extension API: 0.9.0
Python: 3.7.8
python-ly: 0.9.5
Qt: 5.11.3
PyQt: 5.15.0
sip: 4.19.23
poppler: 0.83.0
python-poppler-qt: 0.75.0
OS: Darwin-20.6.0-x86_64-i386-64bit
installation kind: standalone .app bundle

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/widgets/listedit.py", line 95, in itemDoubleClicked
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/widgets/listedit.py", line 111, in editItem
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/preferences/lilypond.py", line 165, in itemChanged
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.7/frescobaldi_app/preferences/lilypond.py", line 181, in display
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

In the current version the code has moved around, but seems to be the same.
I asked for details and to check whether it still happens with 3.3.0.

**Comment by jeanas** [comment]
I see that `lilypondinfo.py` contains

```python
class CachedProperty(cachedproperty.CachedProperty):
    def wait(self, msg=None, timeout=0):
        """Returns the value for the property, waiting for it to be computed.

        If this lasts longer than 2 seconds, a progress dialog is displayed.

        """
        if self.get() is None:
            self.start()
            if self.get() is None:
                if msg is None:
                    msg = _("Running LilyPond, this can take some time...")
                qutil.waitForSignal(self.computed, msg, timeout)
        return self.get()

    __call__ = wait
```

So I guess this might happen if LilyPond takes too much time to respond? The next question is why that's happening in the auto-installation though.
