### ISSUE TITLE
RuntimeError: wrapped C/C   object of type TabBar has been deleted

### ISSUE THREAD

**Issue by ianwest1942** [frescobaldi/frescobaldi#1687]
Traceback (most recent call last):
  File "/Applications/Fre'scobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/macosx/globalmenu.py", line 196, in slot_file_open_recent_action
  File "/Applications/Fre'scobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 433, in openUrl
  File "/Applications/Fre'scobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 457, in openUrls
  File "/Applications/Fre'scobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/app.py", line 106, in openUrl
  File "/Applications/Fre'scobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/document.py", line 246, in new_from_url
RuntimeError: wrapped C/C   object of type TabBar has been deleted

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.3
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.9.0
python-poppler-qt: 21.3.0
OS: macOS-13.4.1-x86_64-i386-64bit
installation kind: standalone .app bundle

**Comment by ianwest1942** [comment]
I don't think you should worry ab out me. I am using Frescobaldi for the first time and VERY RELUCTANTLY. (Only because I cannot use Lilypon 2.24 without. )
I cannot read the tiny font size. I hate the whole interferring pile of junk.
