### ISSUE TITLE
tox i18n setup fails: userguide.mo missing

### ISSUE THREAD

**Issue by sincere-music** [frescobaldi/frescobaldi#1697]
I’m installing frescobaldi on a new system (Linux Mint 21) and had this happen while following the instructions from `INSTALL.md`:

```
simon@simon-desktop:~/frescobaldi/frescobaldi$ tox -e mo-generate && tox -e linux-generate
.tox create: /home/simon/frescobaldi/frescobaldi/.tox/.tox
.tox installdeps: tox >= 4
mo-generate: commands[0]> python i18n/mo-gen.py
i18n/userguide/cs.po:10538: duplicate message definition...
i18n/userguide/cs.po:4396: ...this is the location of the first definition
i18n/userguide/cs.po:10541: duplicate message definition...
i18n/userguide/cs.po:4400: ...this is the location of the first definition
i18n/userguide/cs.po:10544: duplicate message definition...
i18n/userguide/cs.po:4404: ...this is the location of the first definition
i18n/userguide/cs.po:10547: duplicate message definition...
i18n/userguide/cs.po:4408: ...this is the location of the first definition
i18n/userguide/cs.po:10550: duplicate message definition...
i18n/userguide/cs.po:4412: ...this is the location of the first definition
i18n/userguide/cs.po:10553: duplicate message definition...
i18n/userguide/cs.po:4416: ...this is the location of the first definition
i18n/userguide/cs.po:10556: duplicate message definition...
i18n/userguide/cs.po:4420: ...this is the location of the first definition
i18n/userguide/cs.po:10565: duplicate message definition...
i18n/userguide/cs.po:4431: ...this is the location of the first definition
msgfmt: found 8 fatal errors
Traceback (most recent call last):
  File "/home/simon/frescobaldi/frescobaldi/i18n/mo-gen.py", line 18, in <module>
    compile_mo(po, "userguide")
  File "/home/simon/frescobaldi/frescobaldi/i18n/mo-gen.py", line 12, in compile_mo
    molint(out_file)
  File "/home/simon/frescobaldi/frescobaldi/i18n/molint.py", line 37, in molint
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'frescobaldi_app/i18n/cs/LC_MESSAGES/userguide.mo'
mo-generate: exit 1 (0.52 seconds) /home/simon/frescobaldi/frescobaldi> python i18n/mo-gen.py pid=8183
  mo-generate: FAIL code 1 (0.75=setup[0.23]+cmd[0.52] seconds)
  evaluation failed :( (0.79 seconds)
```

**Comment by fedelibre** [comment]
> Looks like the version of Gettext in Ubuntu 22.04 considers that obsolete messages cannot duplicate non-obsolete messages.
> 
> I think we should just get rid of those obsolete messages, they aren't very useful and clutter the files a lot, in addition to this problem.

Are you sure that this analysis is correct?
I can't see why obsolete messages could be a problem. Perhaps there's something wrong with the mo-gen.py script?

In my experience the obsolete messages should be handled by each translator. IIUC they can be useful in case a new string similar to an old one is introduced and some PO editors might offer a translation tip based on the obsolete entry.
See also the last paragraph [here](https://www.gnu.org/software/gettext/manual/html_node/Obsolete-Entries.html).

I don't have strong opinions about obsolete messages though. But could you elaborate why you think the problem is caused by obsolete messages?

**Comment by fedelibre** [comment]
> msgfmt: found 8 fatal errors
> Traceback (most recent call last):
>   File "/home/simon/frescobaldi/frescobaldi/i18n/mo-gen.py", line 18, in <module>
>     compile_mo(po, "userguide")
>   File "/home/simon/frescobaldi/frescobaldi/i18n/mo-gen.py", line 12, in compile_mo
>     molint(out_file)
>   File "/home/simon/frescobaldi/frescobaldi/i18n/molint.py", line 37, in molint
>     with open(filename, 'rb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'frescobaldi_app/i18n/cs/LC_MESSAGES/userguide.mo'

Why is it looking for userguide.mo?

**Comment by fedelibre** [comment]
Thanks for the detailed explanation

> OK, so I stand corrected: the current infrastructure is fine, what was wrong is the way I did this update. I do continue to find obsolete messages not very useful and mildly annoying for scripting (see also [#1686 (comment)](https://github.com/frescobaldi/frescobaldi/pull/1686#issuecomment-1762962430) where the translator misinterpreted them), but if you prefer to only remove the handful of incriminated obsolete messages to fix this issue, it's fine with me.

I don't care much, you can remove all the obsolete messages. I guess they are not useful at all 99% of times...

**Comment by sincere-music** [comment]
Thanks, that fixed it!
