### ISSUE TITLE
RuntimeError: wrapped C/C   object of type QWidget has been deleted

### ISSUE THREAD

**Issue by xmayeur** [frescobaldi/frescobaldi#1699]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/__boot__.py", line 471, in <module>
  File "/Applications/Frescobaldi.app/Contents/Resources/__boot__.py", line 394, in _run
  File "/Applications/Frescobaldi.app/Contents/Resources/frescobaldi", line 50, in <module>
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/app.py", line 157, in run
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 191, in emit
RuntimeError: wrapped C/C   object of type QWidget has been deleted

Décrivez ci-dessous ce que vous faisiez (facultatif) :

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-14.0-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by xmayeur** [comment]
Hello,

For any reasons, I haven't had issue with the installation. The error occurred when exiting Frescobaldi. I don't have the trace, but will send it when reproduced.

By the way, even on macOS Ventura, I always have issues to start Frescobaldi. The welcome screen briefly displays, then I need to click again on the icon in the task bar to open Frescobaldi that regularly hangs, showing all the user interface, but without responding to commands. Usually it correctly starts when I launch Frescobadi from an .ly file and wait a few second before using it 🥸...  

Bonne journée,


Xavier Mayeur
14 rue Thiernesse
1070 Bruxelles
Mobile: +32 (485) 901 434
E-mail: ***@***.***

**Comment by xmayeur** [comment]
Well... I have a Mac, I know Python and have some time, being just retired. So, may I help you to stress test Frescobaldi if someone can give me a crash course on its architecture?Cordialement,Xavier Mayeur.Le 27 oct. 2023 à 12:04, Jean Abou-Samra ***@***.***> a écrit :﻿

For any reasons, I haven't had issue with the installation. The error occurred when exiting Frescobaldi.

So you were able to use Frescobaldi at all, installed from the app bundle, on macOS Sonoma?
It's new to me that this was possible. I thought that everybody would be experiencing #1688, which is about the Carbon library having been removed from macOS.
Maybe Carbon was somehow kept in your upgrade, I don't know...

By the way, even on macOS Ventura, I always have issues to start Frescobaldi. The welcome screen briefly displays, then I need to click again on the icon in the task bar to open Frescobaldi that regularly hangs, showing all the user interface, but without responding to commands. Usually it correctly starts when I launch Frescobadi from an .ly file and wait a few second before using it 🥸...

That one is a known issue, see #428.
