### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by fgohier** [frescobaldi/frescobaldi#1712]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 119, in parse_document
    self.parse_tree(mustree)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 133, in parse_tree
    self.parse_nodes(mus_nodes)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 145, in parse_nodes
    func_call(m)
  File "/usr/lib/python3/dist-packages/ly/musicxml/lymus2musxml.py", line 624, in End
    self.mediator.check_simultan()
  File "/usr/lib/python3/dist-packages/ly/musicxml/ly2xml_mediator.py", line 293, in check_simultan
    self.sections.pop()
IndexError: pop from empty list

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.8.10
Git branch: master
on commit: 7391df98
python-ly: 0.9.5
Qt: 5.12.8
PyQt: 5.14.1
qpageview: 0.6.0
poppler: 0.80.0
python-poppler-qt: 0.24.2
OS: unknown
Installation kind: distro package or installed from source

**Comment by fgohier** [comment]
bonjour,

voici les 3 fichiers que j'ai testé avec le même résultat

merci pour ton aide

Cordialement
Frédéric GOHIER

________________________________
De : Jean Abou-Samra ***@***.***>
Envoyé : jeudi 16 novembre 2023 12:57
À : frescobaldi/frescobaldi ***@***.***>
Cc : fgohier ***@***.***>; Author ***@***.***>
Objet : Re: [frescobaldi/frescobaldi] IndexError: pop from empty list (Issue #1712)


Bonjour Frédéric, est-ce que vous pourriez envoyer le fichier .ly que vous étiez en train de convertir en MusicXML ?

**Comment by fgohier** [comment]
[RE_ [frescobaldi_frescobaldi] IndexError_ pop from empty list (Issue #1712).zip](https://github.com/frescobaldi/frescobaldi/files/13407511/RE_.frescobaldi_frescobaldi.IndexError_.pop.from.empty.list.Issue.1712.zip)

bonjour,

voici les 3 fichiers que j'ai testé avec le même résultat

merci pour ton aide

Cordialement
Frédéric GOHIER

**Comment by fedelibre** [comment]
@jeanas A simple fix has been suggested [here](https://github.com/frescobaldi/python-ly/issues/76). I've not tested  it though.

I'm going on holiday tomorrow, I'll be away from keyboard for a while...

**Comment by ksnortum** [comment]
I tried implementing the simple fix in python-ly, but now CI is failing and I don't know why.

frescobaldi/python-ly#184

**Comment by bmjcode** [comment]
@ksnortum The test itself is the problem, not your code. You can confirm this by running `pytest --runxfail` locally; it fails the same way on your branch and `master`.

The test is hard-coded to expect a specific MusicXML output, but whatever produces that output now formats it slightly differently, so the strings no longer compare equal. When I have time I'll see if I can make that test less brittle.

**Comment by fedelibre** [comment]
We'll mark this as closed when python-ly 0.9.10 is released.

**Comment by fedelibre** [comment]
Let's close it as I'm about to release python-ly 0.9.10 and then Frescobaldi.
