### ISSUE TITLE
RuntimeError: wrapped C/C   object of type QStackedWidget has been deleted

### ISSUE THREAD

**Issue by ttanatb** [frescobaldi/frescobaldi#1730]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/historymanager.py", line 72, in setCurrentDocument
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 191, in emit
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 308, in call
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/historymanager.py", line 83, in _listen
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 186, in setCurrentDocument
RuntimeError: wrapped C/C   object of type QStackedWidget has been deleted

Optionally describe below what you were doing:

Opening a file
[Austin-Wintory-arr-Tanat-Adrift.ly.zip](https://github.com/frescobaldi/frescobaldi/files/14011889/Austin-Wintory-arr-Tanat-Adrift.ly.zip)

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-13.4.1-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by ttanatb** [comment]
Looks like this issue happened when I left my mac to sleep overnight then tried to start working on a file again. Fully exited out of the app and restarted, everything working as intended

**Comment by fedelibre** [comment]
Hopefully fixed in version 4.0.2 by #1935
