### ISSUE TITLE
UnboundLocalError: local variable 'val' referenced before assignment

### ISSUE THREAD

**Issue by xmayeur** [frescobaldi/frescobaldi#1737]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/file_export/__init__.py", line 65, in exportMusicXML
  File "ly/musicxml/lymus2musxml.pyc", line 104, in parse_text
  File "ly/musicxml/lymus2musxml.pyc", line 121, in parse_document
  File "ly/musicxml/lymus2musxml.pyc", line 135, in parse_tree
  File "ly/musicxml/lymus2musxml.pyc", line 147, in parse_nodes
UnboundLocalError: local variable 'val' referenced before assignment

Décrivez ci-dessous ce que vous faisiez (facultatif) :

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-14.3.1-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by fedelibre** [comment]
We may keep this issue open here, but the real one is [issue 80 in python-ly repository](https://github.com/frescobaldi/python-ly/issues/80).
