### ISSUE TITLE
RuntimeError: wrapped C/C   object of type TabBar has been deleted

### ISSUE THREAD

**Issue by leomcf** [frescobaldi/frescobaldi#1738]
Working again correctly after quitting Frescobaldi and restarting. 

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/macosx/globalmenu.py", line 196, in slot_file_open_recent_action
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 433, in openUrl
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 457, in openUrls
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/app.py", line 106, in openUrl
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/document.py", line 246, in new_from_url
RuntimeError: wrapped C/C   object of type TabBar has been deleted

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-14.3-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by jeanas** [comment]
Same as #1467
