### ISSUE TITLE
RuntimeError: wrapped C/C   object of type QAction has been deleted

### ISSUE THREAD

**Issue by humanlanguage** [frescobaldi/frescobaldi#1749]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/preferences/__init__.py", line 112, in done
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/preferences/__init__.py", line 142, in saveSettings
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 191, in emit
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 308, in call
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/actioncollection.py", line 257, in load
RuntimeError: wrapped C/C   object of type QAction has been deleted

Opcionalmente, describa debajo lo que estaba haciendo:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-14.4-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by fedelibre** [comment]
It might be a duplicate of #1679, but let's keep it open. (if one of the two issues must be closed, I'd rather close the older one since we have the user reporting the problem here)

@humanlanguage It would be very useful if you can tell us how to reproduce this error.

**Comment by fedelibre** [comment]
Well, in #1679 the user reported:

> Just close a window and tried to open a new one

but let's keep this issue open and close the other ones.

**Comment by fedelibre** [comment]
Hopefully fixed in version 4.0.2 by #1935
