### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by nicb** [frescobaldi/frescobaldi#1765]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/frescobaldi_app/musicpos.py", line 88, in slotTimeout
    pos = m.time_position(c.position())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ly/music/items.py", line 317, in time_position
    time = e.traverse(n, time, scaling)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ly/music/event.py", line 38, in traverse
    return node.events(self, time, scaling)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ly/music/items.py", line 958, in events
    time = e.traverse(value, time, scaling)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ly/music/event.py", line 38, in traverse
    return node.events(self, time, scaling)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.11.9
python-ly: 0.9.7
Qt: 5.15.13
PyQt: 5.15.10
sip: 6.7.12
qpageview: 0.6.2
poppler: 22.12.0
python-poppler-qt: 21.3.0
OS: Linux-6.7.12-amd64-x86_64-with-glibc2.38

**Comment by fedelibre** [comment]
Can you please advise if this happens when you do something in particular?
There are a number of similar issues: #1572  #1721 #1741 #1756 

#1572 contains some tips to try to debug this error.
