### ISSUE TITLE
RuntimeError: wrapped C/C   object of type MainWindow has been deleted

### ISSUE THREAD

**Issue by antoc1785** [frescobaldi/frescobaldi#1768]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/session.py", line 51, in commitData
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/session.py", line 70, in saveSession
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 427, in writeSessionSettings
RuntimeError: wrapped C/C   object of type MainWindow has been deleted

Opcionalmente, describa debajo lo que estaba haciendo:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.3
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.9.0
python-poppler-qt: 21.3.0
OS: macOS-14.5-x86_64-i386-64bit
installation kind: standalone .app bundle

**Comment by fedelibre** [comment]
There are many similar (with different object types) issues in the tracker.

It would be  helpful to know if you can reproduce the identical error if you do something in particular. Otherwise I'm afraid that all these reports won't be helpful.

**Comment by fedelibre** [comment]
Hopefully fixed in version 4.0.2 by #1935
