### ISSUE TITLE
AttributeError: module 'ly.pkginfo' has no attribute 'name'

### ISSUE THREAD

**Issue by oiram73** [frescobaldi/frescobaldi#1784]
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/frescobaldi_app/file_export/__init__.py", line 64, in exportMusicXML
    writer = ly.musicxml.writer()
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ly/musicxml/__init__.py", line 45, in writer
    return lymus2musxml.ParseSource()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ly/musicxml/lymus2musxml.py", line 68, in __init__
    self.musxml = create_musicxml.CreateMusicXML()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ly/musicxml/create_musicxml.py", line 58, in __init__
    software.text = ly.pkginfo.name   " "   ly.pkginfo.version
                    ^^^^^^^^^^^^^^^
AttributeError: module 'ly.pkginfo' has no attribute 'name'

È possibile descrivere sotto quel che si stava facendo:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.12.4
python-ly: 0.9.8
Qt: 5.15.14
PyQt: 5.15.11
sip: 6.8.6
qpageview: 0.6.2
poppler: 24.3.0
python-poppler-qt: 21.3.0
OS: Linux-6.10.5-1-MANJARO-x86_64-with-glibc2.40

**Comment by fedelibre** [comment]
Yes, I found this bug [3 weeks ago](https://github.com/frescobaldi/python-ly/commit/233de7e253086c3eaad21c5b5223169832b36282#commitcomment-146896968). It's a python-ly bug.

The next release of python-ly will fix it.
You can manually apply that fix in the meanwhile.

**Comment by fedelibre** [comment]
I'll close this issue. Hopefully we'll have a new release before Christmas
