### ISSUE TITLE
RuntimeError: wrapped C/C   object of type PagedView has been deleted

### ISSUE THREAD

**Issue by yoshiakionishi** [frescobaldi/frescobaldi#1789]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/preferences/__init__.py", line 142, in saveSettings
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 191, in emit
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 308, in call
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/pagedview.py", line 113, in readSettings
RuntimeError: wrapped C/C   object of type PagedView has been deleted

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-14.6.1-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by yoshiakionishi** [comment]
I tried to click "Apply" in Preferences and gave this error.

**Comment by fedelibre** [comment]
Thanks for the report.

#1467 remains the main issue to follow for this kind of error.

**Comment by fedelibre** [comment]
Hopefully fixed in version 4.0.2 by #1935
