### ISSUE TITLE
RuntimeError: wrapped C/C   object of type View has been deleted

### ISSUE THREAD

**Issue by bofolan** [frescobaldi/frescobaldi#1809]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/macosx/file_open_eventhandler.py", line 58, in eventFilter
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/macosx/file_open_eventhandler.py", line 52, in openUrl
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/mainwindow.py", line 186, in setCurrentDocument
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/viewmanager.py", line 241, in setCurrentDocument
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/viewmanager.py", line 135, in document
RuntimeError: wrapped C/C   object of type View has been deleted

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.3
PyQt: 5.15.7
sip: 6.6.2
qpageview: 0.6.2
poppler: 22.9.0
python-poppler-qt: 21.3.0
OS: macOS-12.7.6-x86_64-i386-64bit
installation kind: standalone .app bundle

**Comment by bofolan** [comment]
I really don't understand what happened!

**Comment by bmjcode** [comment]
This is a longstanding problem on macOS (we're tracking it under #1467). The short answer is we think it's a bug with how the Mac version is packaged, but it's been tricky to resolve since most of us developing Frescobaldi are not Mac users.

I'm hoping the switch to Qt 6 will help to address this in our next version.

**Comment by bofolan** [comment]
Can I run lilypond without frescobaldi for now?

Regards

**Comment by ksnortum** [comment]
You can run LilyPond on the command line without Frescobaldi.

https://lilypond.org/doc/v2.24/Documentation/usage/command_002dline-usage
