### ISSUE TITLE
AttributeError: type object 'QPinchGesture' has no attribute 'ScaleFactorChanged'

### ISSUE THREAD

**Issue by JunTamura1959** [frescobaldi/frescobaldi#1822]
This seems to happen whenever you try to use "pinch" gesture to scale the music view.

Traceback (most recent call last):
  File "/Users/tamura/frescobaldi_git/frescobaldi/frescobaldi_app/qpageview/link.py", line 212, in event
    return super().event(ev)
           ^^^^^^^^^^^^^^^^^
  File "/Users/tamura/frescobaldi_git/frescobaldi/frescobaldi_app/qpageview/view.py", line 1037, in event
    if isinstance(ev, QGestureEvent) and self.handleGestureEvent(ev):
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamura/frescobaldi_git/frescobaldi/frescobaldi_app/qpageview/view.py", line 1052, in handleGestureEvent
    return self.pinchGesture(pinch)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tamura/frescobaldi_git/frescobaldi/frescobaldi_app/qpageview/view.py", line 1069, in pinchGesture
    if changeFlags & QPinchGesture.ScaleFactorChanged:
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QPinchGesture' has no attribute 'ScaleFactorChanged'

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.12.7
Git branch: master
on commit: 74ad5472
python-ly: 0.9.8
Qt: 6.8.0
PyQt: 6.8.0.dev2410211537
qpageview: 0.6.2
OS: macOS-15.1.1-x86_64-i386-64bit
installation kind: command line

**Comment by bmjcode** [comment]
This is actually a qpageview bug. PyQt6 changed how enum values are named, so what was `QPinchGesture.ScaleFactorChanged` is now `QPinchGesture.ChangeFlag.ScaleFactorChanged`. I missed this one earlier but just submitted a PR to fix it.
