### ISSUE TITLE
UnboundLocalError: cannot access local variable 'val' where it is not associated with a value

### ISSUE THREAD

**Issue by kjcole** [frescobaldi/frescobaldi#1831]
While using the flatpak and attempting to export a file in MusicXML format...

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/frescobaldi_app/file_export/__init__.py", line 65, in exportMusicXML
    writer.parse_text(doc.toPlainText(), orgname)
  File "/app/lib/python3.11/site-packages/ly/musicxml/lymus2musxml.py", line 104, in parse_text
    self.parse_document(doc)
  File "/app/lib/python3.11/site-packages/ly/musicxml/lymus2musxml.py", line 121, in parse_document
    self.parse_tree(mustree)
  File "/app/lib/python3.11/site-packages/ly/musicxml/lymus2musxml.py", line 135, in parse_tree
    self.parse_nodes(mus_nodes)
  File "/app/lib/python3.11/site-packages/ly/musicxml/lymus2musxml.py", line 147, in parse_nodes
    func_call(m)
UnboundLocalError: cannot access local variable 'val' where it is not associated with a value

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.11.9
python-ly: 0.9.8
Qt: 5.15.10
PyQt: 5.15.11
sip: 6.8.6
qpageview: 0.6.2
poppler: 21.8.0
python-poppler-qt: 21.3.0
OS: Linux-6.9.3-76060903-generic-x86_64-with-glibc2.38

**Comment by fedelibre** [comment]
Can you share the LilyPond file you are trying to export? Either a minimal example if possible or the full version (even privately in case it's copyrighted music).

**Comment by kjcole** [comment]
> Can you share the LilyPond file you are trying to export? Either a minimal example if possible or the full version (even privately in case it's copyrighted music).

Since I haven't a clue as to what's causing the trouble, nor, for that matter, which bits get converted to  MusicXML I have no idea what a "minimal example" would be. It's not (yet) copyrighted, as it's mine. So, I'm just going to include it all here and hope it's not too much. (101 lines, none very complicated,  after eliminating all the comments, the MIDI generation, and the fretboard diagrams.). But, running it from the terminal I see a bunch of warnings when I issue the Export to MusicXML, that I may need to take care of:

```
Warning: MarkupCommand not implemented!
'ParseSource' object has no attribute 'MarkupCommand'
Warning: MarkupCommand not implemented!
'ParseSource' object has no attribute 'MarkupCommand'
Warning: MarkupCommand not implemented!
'ParseSource' object has no attribute 'MarkupCommand'
Context not implemented: ChordNames
Warning: ChordSpecifier not implemented!
'ParseSource' object has no attribute 'ChordSpecifier'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordSpecifier not implemented!
'ParseSource' object has no attribute 'ChordSpecifier'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordSpecifier not implemented!
'ParseSource' object has no attribute 'ChordSpecifier'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordSpecifier not implemented!
'ParseSource' object has no attribute 'ChordSpecifier'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Context not implemented: FretBoards
Warning: ChordSpecifier not implemented!
'ParseSource' object has no attribute 'ChordSpecifier'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordSpecifier not implemented!
'ParseSource' object has no attribute 'ChordSpecifier'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordSpecifier not implemented!
'ParseSource' object has no attribute 'ChordSpecifier'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordSpecifier not implemented!
'ParseSource' object has no attribute 'ChordSpecifier'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
Warning: ChordItem not implemented!
'ParseSource' object has no attribute 'ChordItem'
```
[mwe-ly.txt](https://github.com/user-attachments/files/17977817/mwe-ly.txt)
