### ISSUE TITLE
KeyError: <document.EditorDocument object at 0x1500e88b0>

### ISSUE THREAD

**Issue by royabradley** [frescobaldi/frescobaldi#1844]
Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/document.py", line 259, in slotModificationChanged
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 191, in emit
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/signals.py", line 308, in call
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python3.10/frescobaldi_app/documentmenu.py", line 112, in setDocumentStatus
KeyError: <document.EditorDocument object at 0x1500e88b0>

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.10
python-ly: 0.9.7
Qt: 5.15.8
PyQt: 5.15.9
sip: 6.7.6
qpageview: 0.6.2
poppler: 23.3.0
python-poppler-qt: 21.3.0
OS: macOS-15.1.1-arm64-arm-64bit
installation kind: standalone .app bundle

**Comment by bmjcode** [comment]
We have a new release coming soon that will hopefully fix this.
