### ISSUE TITLE
incorrect error parsing

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#668]
Reported by a user:

```
Frescobaldi: 2.18

Python: 2.7.9 -- Qt: 4.8.6 -- PyQt4: 4.11.3 -- sip: 4.16.6
python-ly: 0.9.1
poppler: 0.31.0 -- python-poppler-qt4: 0.24.0
OS: Darwin-14.1.0-x86_64-i386-64bit

Traceback (most recent call last):
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/logtool/logwidget.py", line 137, in slotAnchorClicked
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/logtool/logwidget.py", line 169, in highlightError
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/logtool/errors.py", line 109, in cursor
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/logtool/errors.py", line 175, in cursor
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/app.py", line 85, in openUrl
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/document.py", line 73, in new_from_url
  File "/Applications/Frescobaldi.app/Contents/Resources/lib/python2.7/frescobaldi_app/document.py", line 60, in load_data
IOError: [Errno 2] No such file or directory: u'Preprocessing graphical objects.../Users/paul/lilypond_stuff/includes/clairnote-code-next.ly'

Optionally describe below what you were doing:

Clicking on an error message in the log to see where it was occurring in the .ly file.
```

This issue is two bugs: the file name in the error message should be parsed correctly, but also we shouldn't let app.openUrl() bail out when a file does not exist.

**Comment by fedelibre** [comment]
This is quite old. Can be closed?

**Comment by wbsoft** [comment]
not sure, but we always can reopen :)
